import '../game_contents.dart';

final List<GameContents> churchFour = [
  GameContents(name: '아브 _ _', index: '1'),
  GameContents(name: '사도 _ _', index: '2'),
  GameContents(name: '요한 _ _', index: '3'),
  GameContents(name: '주기 _ _', index: '4'),
  GameContents(name: '느헤 _ _', index: '5'),
  GameContents(name: '예레 _ _', index: '6'),
  GameContents(name: '이스 _ _', index: '7'),
  GameContents(name: '예루 _ _', index: '8'),
  GameContents(name: '스룹 _ _', index: '9'),
  GameContents(name: '시드 _ _', index: '10'),
  GameContents(name: '여호 _ _', index: '11'),
  GameContents(name: '여로 _ _', index: '12'),
  GameContents(name: '히스 _ _', index: '13'),
  GameContents(name: '천지 _ _', index: '14'),
  GameContents(name: '가브 _ _', index: '15'),
  GameContents(name: '마태 _ _', index: '16'),
  GameContents(name: '사마 _ _', index: '17'),
  GameContents(name: '에벤 _ _', index: '18'),
  GameContents(name: '가버 _ _', index: '19'),
  GameContents(name: '겟세 _ _', index: '20'),
  GameContents(name: '마라 _ _', index: '21'),
  GameContents(name: '임마 _ _', index: '22'),
  GameContents(name: '므두 _ _', index: '23'),
  GameContents(name: '그리 _ _', index: '24'),
  GameContents(name: '동방 _ _', index: '25'),
  GameContents(name: '골로 _ _', index: '26'),
  GameContents(name: '공관 _ _', index: '27'),
  GameContents(name: '베들 _ _', index: '28'),
  GameContents(name: '바돌 _ _', index: '29'),
  GameContents(name: '바리 _ _', index: '30'),
  GameContents(name: '오병 _ _', index: '31'),
  GameContents(name: '아비 _ _', index: '32'),
  GameContents(name: '나다 _ _', index: '33'),
  GameContents(name: '르호 _ _', index: '34'),
  GameContents(name: '출애 _ _', index: '35'),
  GameContents(name: '사무 _ _', index: '36'),
  GameContents(name: '열왕 _ _', index: '37'),
  GameContents(name: '마가 _ _', index: '38'),
  GameContents(name: '누가 _ _', index: '39'),
  GameContents(name: '사도 _ _', index: '40'),
  GameContents(name: '에베 _ _', index: '41'),
  GameContents(name: '빌립 _ _', index: '42'),
  GameContents(name: '빌레 _ _', index: '43'),
  GameContents(name: '야고 _ _', index: '44'),
  GameContents(name: '히브 _ _', index: '45'),
  GameContents(name: '히네 _ _', index: '46'),
  GameContents(name: '사복 _ _', index: '47'),
  GameContents(name: '삼위 _ _', index: '48'),
  GameContents(name: '사도 _ _', index: '49'),
  GameContents(name: '세례 _ _', index: '50'),
];

final List<GameContents> churchDisco = [
  GameContents(name: '사랑', index: '1'),
  GameContents(name: '거룩', index: '2'),
  GameContents(name: '피(보혈)', index: '3'),
  GameContents(name: '죄', index: '4'),
  GameContents(name: '감사', index: '5'),
  GameContents(name: '하늘', index: '6'),
  GameContents(name: '하나님', index: '7'),
  GameContents(name: '우리', index: '8'),
  GameContents(name: '나', index: '9'),
  GameContents(name: '믿음', index: '10'),
  GameContents(name: '삶', index: '11'),
  GameContents(name: '생명', index: '12'),
  GameContents(name: '성령', index: '13'),
  GameContents(name: '예수', index: '14'),
  GameContents(name: '아침', index: '15'),
  GameContents(name: '영광', index: '16'),
  GameContents(name: '예배', index: '17'),
  GameContents(name: '주님', index: '18'),
  GameContents(name: '자유', index: '19'),
  GameContents(name: '친구', index: '20'),
  GameContents(name: '구주', index: '21'),
  GameContents(name: '아버지', index: '22'),
  GameContents(name: '목자', index: '23'),
  GameContents(name: '마음', index: '24'),
  GameContents(name: '찬양', index: '25'),
  GameContents(name: '경배', index: '26'),
  GameContents(name: '아름', index: '27'),
  GameContents(name: '세상', index: '28'),
  GameContents(name: '빛', index: '29'),
  GameContents(name: '복음', index: '30'),
  GameContents(name: '비', index: '31'),
  GameContents(name: '능력', index: '32'),
  GameContents(name: '오늘', index: '33'),
  GameContents(name: '기도', index: '34'),
  GameContents(name: '성도', index: '35'),
  GameContents(name: '영원', index: '36'),
  GameContents(name: '이름', index: '37'),
  GameContents(name: '길', index: '38'),
  GameContents(name: '영혼', index: '39'),
  GameContents(name: '보좌', index: '40'),
  GameContents(name: '매일', index: '41'),
  GameContents(name: '춤', index: '42'),
  GameContents(name: '기쁨', index: '43'),
  GameContents(name: '찬송', index: '44'),
  GameContents(name: '소망', index: '45'),
  GameContents(name: '얼굴', index: '46'),
  GameContents(name: '갈급', index: '47'),
  GameContents(name: '창조', index: '48'),
  GameContents(name: '모든', index: '49'),
  GameContents(name: '슬픔', index: '50')
];

final List<GameContents> churchCaptain = [
  GameContents(answer: '커서 목사님\n될 것 같은 사람', index: '1'),
  GameContents(answer: '기도하다가\n졸 것 같은 사람', index: '2'),
  GameContents(answer: '찬양할 때 칼로리 소모\n가장 많이 할 것 같은 사람', index: '3'),
  GameContents(answer: '어릴 때 교회 선생님 속\n많이 썩였을 것 같은 사람', index: '4'),
  GameContents(answer: '교회 엄친아/엄친딸\n일 것 같은 사람', index: '5'),
  GameContents(answer: '밖에서 전도\n잘 할 것 같은 사람', index: '6'),
  GameContents(answer: '첫인상과 지금이\n가장 다른 사람', index: '7'),
  GameContents(answer: '교회와 집에서 모습이\n똑같을 것 같은 사람', index: '8'),
  GameContents(answer: '교회 물건 가장 잘\n고장 낼 것 같은 사람', index: '9'),
  GameContents(answer: '어릴 때 교회누나/오빠 보러\n교회 왔을 것 같은 사람', index: '10'),
  GameContents(answer: '본인이 생각하는 성경인물과\n가장 유사한 사람', index: '11'),
  GameContents(answer: '지금 제일 집가고\n싶어하는 것 같은 사람', index: '12'),
  GameContents(answer: '교회올 때 가장 늦게\n일어날 것 같은 사람', index: '13'),
  GameContents(answer: '예수님 안믿었으면\n큰일날 것 같은 사람', index: '14'),
  GameContents(answer: '주일학교 회장하면\n제일 잘할 것 같은 사람', index: '15'),
  GameContents(answer: '성경 1회독\n해봤을 것 같은 사람', index: '16'),
  GameContents(answer: '거짓말 제일\n잘할 것 같은 사람', index: '17'),
  GameContents(answer: '학생 때 가장\n잘 놀았을 것 같은 사람', index: '18'),
  GameContents(answer: '어릴 때 사고\n많이 쳤을 것 같은 사람', index: '19'),
  GameContents(answer: '다니엘처럼 사자굴에서도\n기도할 것 같은 사람', index: '20'),
  GameContents(answer: '요나처럼 물고기 뱃속에서도\n잘 살 것 같은 사람', index: '21'),
];
