class GameContents {
  String name;
  String index;
  String answer;

  GameContents({
    this.name = '',
    required this.index,
    this.answer = '',
  });
}

class UpDownGameContents {
  String name;
  String explain1;
  String explain2;
  String index;
  String answer;

  UpDownGameContents({
    this.name = '',
    this.explain1 = '',
    this.explain2 = '',
    required this.index,
    this.answer = '',
  });
}

class SizeUpGameContents {
  String name;
  String index;
  String answer;
  String explain;

  SizeUpGameContents({
    this.name = '',
    required this.index,
    this.answer = '',
    required this.explain,
  });
}

final List<GameContents> person = [
  GameContents(name: 'assets/person/강동원.WEBP', index: '1'),
  GameContents(name: 'assets/person/류승범.WEBP', index: '2'),
  GameContents(name: 'assets/person/남도일.jpeg', index: '3'),
  GameContents(name: 'assets/person/강백호.jpeg', index: '4'),
  GameContents(name: 'assets/person/공유.WEBP', index: '5'),
  GameContents(name: 'assets/person/미나.WEBP', index: '6'),
  GameContents(name: 'assets/person/김태희.jpeg', index: '7'),
  GameContents(name: 'assets/person/송혜교.WEBP', index: '8'),
  GameContents(name: 'assets/person/박재범.WEBP', index: '9'),
  GameContents(name: 'assets/person/수지.JPG', index: '10'),
  GameContents(name: 'assets/person/김동현.WEBP', index: '11'),
  GameContents(name: 'assets/person/링컨.WEBP', index: '12'),
  GameContents(name: 'assets/person/유관순.WEBP', index: '13'),
  GameContents(name: 'assets/person/데드풀.jpeg', index: '14'),
  GameContents(name: 'assets/person/로버트 다우니 주니어.jpeg', index: '15'),
  GameContents(name: 'assets/person/민경훈.jpeg', index: '16'),
  GameContents(name: 'assets/person/보노보노.WEBP', index: '17'),
  GameContents(name: 'assets/person/스칼렛요한슨.JPG', index: '18'),
  GameContents(name: 'assets/person/올라프.JPG', index: '19'),
  GameContents(name: 'assets/person/이승우.jpeg', index: '20'),
  GameContents(name: 'assets/person/안재홍.WEBP', index: '21'),
  GameContents(name: 'assets/person/손흥민.JPG', index: '22'),
  GameContents(name: 'assets/person/강하늘.WEBP', index: '23'),
  GameContents(name: 'assets/person/거미.WEBP', index: '24'),
  GameContents(name: 'assets/person/고윤정.WEBP', index: '25'),
  GameContents(name: 'assets/person/미달이.WEBP', index: '26'),
  GameContents(name: 'assets/person/뿡뿡이.WEBP', index: '27'),
  GameContents(name: 'assets/person/어피치.png', index: '28'),
  GameContents(name: 'assets/person/해린.JPG', index: '29'),
  GameContents(name: 'assets/person/저스틴 비버.png', index: '30'),
  GameContents(name: 'assets/person/조정석.WEBP', index: '31'),
  GameContents(name: 'assets/person/조유리.png', index: '32'),
  GameContents(name: 'assets/person/정동원.jpeg', index: '33'),
  GameContents(name: 'assets/person/무민.JPG', index: '34'),
  GameContents(name: 'assets/person/샘스미스.WEBP', index: '35'),
  GameContents(name: 'assets/person/현주엽.WEBP', index: '36'),
  GameContents(name: 'assets/person/전여빈.WEBP', index: '37'),
  GameContents(name: 'assets/person/김연경.jpeg', index: '38'),
  GameContents(name: 'assets/person/타노스.WEBP', index: '39'),
  GameContents(name: 'assets/person/김소연.WEBP', index: '40'),
  GameContents(name: 'assets/person/조승우.JPG', index: '41'),
  GameContents(name: 'assets/person/안나.JPG', index: '42'),
  GameContents(name: 'assets/person/포돌이.WEBP', index: '43'),
  GameContents(name: 'assets/person/이문세.WEBP', index: '44'),
  GameContents(name: 'assets/person/문상훈.WEBP', index: '45'),
  GameContents(name: 'assets/person/지성.WEBP', index: '46'),
  GameContents(name: 'assets/person/이경영.WEBP', index: '47'),
  GameContents(name: 'assets/person/피오나.WEBP', index: '48'),
  GameContents(name: 'assets/person/윈터.jpeg', index: '49'),
  GameContents(name: 'assets/person/고아성.WEBP', index: '50'),
  GameContents(name: 'assets/person/김연자.jpeg', index: '51'),
  GameContents(name: 'assets/person/마동석.jpeg', index: '52'),
  GameContents(name: 'assets/person/임영웅.jpeg', index: '53'),
  GameContents(name: 'assets/person/장윤주.jpeg', index: '54'),
  GameContents(name: 'assets/person/차두리.jpeg', index: '55'),
  GameContents(name: 'assets/person/나영석.WEBP', index: '56'),
  GameContents(name: 'assets/person/노진구.JPG', index: '57'),
  GameContents(name: 'assets/person/유해진.WEBP', index: '58'),
  GameContents(name: 'assets/person/최우식.JPG', index: '59'),
  GameContents(name: 'assets/person/크러쉬.JPG', index: '60'),
  GameContents(name: 'assets/person/박명수.WEBP', index: '61'),
  GameContents(name: 'assets/person/봉준호.WEBP', index: '62'),
  GameContents(name: 'assets/person/일론 머스크.WEBP', index: '63'),
  GameContents(name: 'assets/person/안유진.JPG', index: '64'),
  GameContents(name: 'assets/person/아이유.jpeg', index: '65'),
  GameContents(name: 'assets/person/장원영.jpg', index: '66'),
  GameContents(name: 'assets/person/유재석.webp', index: '67'),
  GameContents(name: 'assets/person/조세호.jpg', index: '68'),
  GameContents(name: 'assets/person/카리나.png', index: '69'),
  GameContents(name: 'assets/person/뽀로로.jpg', index: '70'),
  GameContents(name: 'assets/person/도라에몽.jpg', index: '71'),
  GameContents(name: 'assets/person/미키마우스.webp', index: '72'),
  GameContents(name: 'assets/person/하니.jpg', index: '73'),
  GameContents(name: 'assets/person/제니.webp', index: '74'),
  GameContents(name: 'assets/person/뷔.png', index: '75'),
  GameContents(name: 'assets/person/박보검.png', index: '76'),
  GameContents(name: 'assets/person/오은영.webp', index: '77'),
  GameContents(name: 'assets/person/김태리.webp', index: '78'),
  GameContents(name: 'assets/person/손석구.jpg', index: '79'),
  GameContents(name: 'assets/person/나문희.webp', index: '80'),
  GameContents(name: 'assets/person/박서준.jpg', index: '81'),
  GameContents(name: 'assets/person/박진영.jpg', index: '82'),
  GameContents(name: 'assets/person/스티브잡스.webp', index: '83'),
  GameContents(name: 'assets/person/이제훈.jpeg', index: '84'),
  GameContents(name: 'assets/person/티모시 샬라메.jpg', index: '85'),
  GameContents(name: 'assets/person/한소희.jpg', index: '86'),
];

final List<GameContents> disco = [
  GameContents(name: '사랑', index: '1'),
  GameContents(name: '너', index: '2'),
  GameContents(name: '나', index: '3'),
  GameContents(name: '우리', index: '4'),
  GameContents(name: '봄', index: '5'),
  GameContents(name: '여름', index: '6'),
  GameContents(name: '가을', index: '7'),
  GameContents(name: '겨울', index: '8'),
  GameContents(name: '당신', index: '9'),
  GameContents(name: '미안', index: '10'),
  GameContents(name: '손', index: '11'),
  GameContents(name: '바다', index: '12'),
  GameContents(name: '하늘', index: '13'),
  GameContents(name: '엄마', index: '14'),
  GameContents(name: '이별', index: '15'),
  GameContents(name: '눈물', index: '16'),
  GameContents(name: '꽃', index: '17'),
  GameContents(name: '서로', index: '18'),
  GameContents(name: '인연', index: '19'),
  GameContents(name: '널', index: '20'),
  GameContents(name: '안녕', index: '21'),
  GameContents(name: '진심', index: '22'),
  GameContents(name: '마음', index: '23'),
  GameContents(name: 'Love', index: '24'),
  GameContents(name: 'You', index: '25'),
  GameContents(name: 'Baby', index: '26'),
  GameContents(name: '인사', index: '27'),
  GameContents(name: '눈', index: '28'),
  GameContents(name: '비', index: '29'),
  GameContents(name: '바람', index: '30'),
  GameContents(name: '생각', index: '31'),
  GameContents(name: '가슴', index: '32'),
  GameContents(name: '고백', index: '33'),
  GameContents(name: '우주', index: '34'),
  GameContents(name: '별', index: '35'),
  GameContents(name: 'star', index: '36'),
  GameContents(name: '나무', index: '37'),
  GameContents(name: '자유', index: '38'),
  GameContents(name: '미련', index: '39'),
  GameContents(name: '정말', index: '40'),
  GameContents(name: '행복', index: '41'),
  GameContents(name: '하루', index: '42'),
  GameContents(name: '거짓말', index: '43'),
  GameContents(name: '풍선', index: '44'),
  GameContents(name: 'bye', index: '45'),
  GameContents(name: 'my', index: '46'),
  GameContents(name: '오늘', index: '47'),
  GameContents(name: '어제', index: '48'),
  GameContents(name: '내일', index: '49'),
  GameContents(name: '친구', index: '50'),
  GameContents(name: '꿀 honey', index: '51'),
  GameContents(name: '꿈', index: '52'),
  GameContents(name: '밤', index: '53'),
  GameContents(name: '낮', index: '54'),
];

final List<GameContents> captain = [
  GameContents(
      name: '가장 유연할\n것 같은 사람', answer: '옆사람과 다리찢기\n가위바위보 해서 이기기', index: '1'),
  GameContents(name: '가장 노래를 잘\n부를 것 같은 사람', answer: '절대음감', index: '2'),
  GameContents(name: '대머리가 제일 잘\n어울릴 것 같은 사람', answer: '이마 길이 재기', index: '3'),
  GameContents(name: '공부 제일 잘할\n것 같은 사람', answer: '구구단 10문제 맞추기', index: '4'),
  GameContents(name: '가장 춤 잘출\n것 같은 사람', answer: '포스트잇 빨리 떼기', index: '5'),
  GameContents(name: '가장 운동 잘할\n것 같은 사람', answer: '한 발 들고\n오래 버티기', index: '6'),
  GameContents(name: '수업 시간에 졸\n것 같은 사람', answer: '옆사람과 눈싸움해서 이기기', index: '7'),
  GameContents(
      name: '고등학생 때 담 넘어봤을\n것 같은 사람', answer: '멀리뛰기 \n가장 멀리뛰기', index: '8'),
  GameContents(name: '정색 가장 잘할\n것 같은 사람', answer: '1분 동안 웃음 참기', index: '9'),
  GameContents(
      name: '가장 당당해 보이는 사람', answer: '옆사람과 당연하지 게임 해서 이기기', index: '10'),
  GameContents(name: '사회생활 잘할 \n것 같은 사람', answer: '눈치게임', index: '11'),
  GameContents(name: '눈물 많을\n것 같은 사람', answer: '눈물 빨리 흘리기', index: '12'),
  GameContents(
      name: '무인도에서 살아남을 수\n있을 것 같은 사람',
      answer: '무인도에 가져갈 물건 사람들 앞에서 PT하고 납득시키기',
      index: '13'),
  GameContents(
      name: '과자를 가장 많이 먹을\n것 같은 사람', answer: '과자 부스러기 보고\n과자 맞추기', index: '14'),
  GameContents(name: '요리 잘 할\n것 같은 사람', answer: '후라이펜 놀이', index: '15'),
  GameContents(name: '끈기 있는 사람', answer: '페트병 빨리 세우기', index: '16'),
  GameContents(
      name: '문자보다 전화를 더 좋아할 것 같은 사람',
      answer: '가장 최근 연락한 사람에게 전화해서 칭찬 듣기',
      index: '17'),
  GameContents(
      name: 'SNS 가장 많이 할\n것 같은 사람',
      answer: '눈 감고 오늘 자신의 TMI를 타자로 치기',
      index: '18'),
  GameContents(
      name: '감수성이 가장 풍부할\n것 같은 사람', answer: '자신의 이름으로 삼행시 짓기', index: '19'),
  GameContents(
      name: '연애 제일 많이 해봤을거 같은 사람', answer: '가족에게 전화해서 사랑한다고 말하기', index: '20'),
];

final List<GameContents> choi = [
  GameContents(name: 'ㄷ ㅁ', index: '1'),
  GameContents(name: 'ㅁ ㄹ', index: '2'),
  GameContents(name: 'ㄱ ㄷ', index: '3'),
  GameContents(name: 'ㅈ ㄱ', index: '4'),
  GameContents(name: 'ㄴ ㅇ', index: '5'),
  GameContents(name: 'ㄱ ㄹ', index: '6'),
  GameContents(name: 'ㅁ ㄱ', index: '7'),
  GameContents(name: 'ㄱ ㅅ', index: '8'),
  GameContents(name: 'ㄷ ㄹ', index: '9'),
  GameContents(name: 'ㅎ ㅎ', index: '10'),
  GameContents(name: 'ㄱ ㅇ', index: '11'),
  GameContents(name: 'ㅅ ㄷ', index: '12'),
  GameContents(name: 'ㅇ ㅈ', index: '13'),
  GameContents(name: 'ㅂ ㅇ', index: '14'),
  GameContents(name: 'ㄴ ㄱ', index: '15'),
  GameContents(name: 'ㄱ ㅂ', index: '16'),
  GameContents(name: 'ㅂ ㅈ', index: '17'),
  GameContents(name: 'ㅇ ㄱ', index: '18'),
  GameContents(name: 'ㅅ ㄱ', index: '19'),
  GameContents(name: 'ㄴ ㄹ', index: '20'),
  GameContents(name: 'ㄱ ㅊ', index: '21'),
  GameContents(name: 'ㅂ ㅁ', index: '22'),
  GameContents(name: 'ㄴ ㅂ', index: '23'),
  GameContents(name: 'ㅇ ㅁ', index: '24'),
  GameContents(name: 'ㄷ ㄱ', index: '25'),
  GameContents(name: 'ㄱ ㄱ', index: '26'),
  GameContents(name: 'ㅅ ㅁ', index: '27'),
  GameContents(name: 'ㅁ ㅁ', index: '28'),
  GameContents(name: 'ㄷ ㅂ', index: '29'),
  GameContents(name: 'ㅂ ㅈ', index: '30'),
  GameContents(name: 'ㄱ ㅈ', index: '31'),
  GameContents(name: 'ㅁ ㅇ', index: '32'),
  GameContents(name: 'ㅅ ㅈ', index: '33'),
  GameContents(name: 'ㅍ ㄹ', index: '34'),
  GameContents(name: 'ㅁ ㅂ', index: '35'),
  GameContents(name: 'ㄴ ㅁ', index: '36'),
  GameContents(name: 'ㅎ ㅇ', index: '37'),
  GameContents(name: 'ㄷ ㅇ', index: '38'),
  GameContents(name: 'ㅂ ㅅ', index: '39'),
  GameContents(name: 'ㅅ ㄹ', index: '40'),
  GameContents(name: 'ㅇ ㅅ', index: '41'),
  GameContents(name: 'ㅂ ㄱ', index: '42'),
  GameContents(name: 'ㄷ ㅈ', index: '43'),
  GameContents(name: 'ㅈ ㅅ', index: '44'),
  GameContents(name: 'ㅅ ㅇ', index: '45'),
  GameContents(name: 'ㅇ ㄹ', index: '46'),
  GameContents(name: 'ㅂ ㅎ', index: '47'),
  GameContents(name: 'ㅎ ㅅ', index: '48'),
  GameContents(name: 'ㅇ ㅂ', index: '49'),
  GameContents(name: 'ㅂ ㅂ', index: '50'),
];
final List<GameContents> four = [
  GameContents(name: '이구 _ _', index: '1'),
  GameContents(name: '동문 _ _', index: '2'),
  GameContents(name: '드라 _ _', index: '3'),
  GameContents(name: '게르 _ _', index: '4'),
  GameContents(name: '안전 _ _', index: '5'),
  GameContents(name: '고슴 _ _', index: '6'),
  GameContents(name: '오토 _ _', index: '7'),
  GameContents(name: '파인 _ _', index: '8'),
  GameContents(name: '레이 _ _', index: '9'),
  GameContents(name: '예방 _ _', index: '10'),
  GameContents(name: '고객 _ _', index: '11'),
  GameContents(name: '샌드 _ _', index: '12'),
  GameContents(name: '유통 _ _', index: '13'),
  GameContents(name: '호랑 _ _', index: '14'),
  GameContents(name: '술래 _ _', index: '15'),
  GameContents(name: '프리 _ _', index: '16'),
  GameContents(name: '분리 _ _', index: '17'),
  GameContents(name: '초코 _ _', index: '18'),
  GameContents(name: '해바 _ _', index: '19'),
  GameContents(name: '코스 _ _', index: '20'),
  GameContents(name: '카놀 _ _', index: '21'),
  GameContents(name: '어린 _ _', index: '22'),
  GameContents(name: '일기 _ _', index: '23'),
  GameContents(name: '백설 _ _', index: '24'),
  GameContents(name: '헤드 _ _', index: '25'),
  GameContents(name: '보사 _ _', index: '26'),
  GameContents(name: '폼클 _ _', index: '27'),
  GameContents(name: '오랑 _ _', index: '28'),
  GameContents(name: '나무 _ _', index: '29'),
  GameContents(name: '차돌 _ _', index: '30'),
  GameContents(name: '치즈 _ _', index: '31'),
  GameContents(name: '다이 _ _', index: '32'),
  GameContents(name: '김치 _ _', index: '33'),
  GameContents(name: '자급 _ _', index: '34'),
  GameContents(name: '다이 _ _', index: '35'),
  GameContents(name: '다사 _ _', index: '36'),
  GameContents(name: '이모 _ _', index: '37'),
  GameContents(name: '장기 _ _', index: '38'),
  GameContents(name: '인테 _ _', index: '39'),
  GameContents(name: '감자 _ _', index: '40'),
  GameContents(name: '직사 _ _', index: '41'),
  GameContents(name: '계란 _ _', index: '42'),
  GameContents(name: '피라 _ _', index: '43'),
  GameContents(name: '와이 _ _', index: '44'),
  GameContents(name: '무당 _ _', index: '45'),
  GameContents(name: '페이 _ _', index: '46'),
  GameContents(name: '아나 _ _', index: '47'),
  GameContents(name: '개미 _ _', index: '48'),
  GameContents(name: '코카 _ _', index: '49'),
  GameContents(name: '오피 _ _', index: '50'),
  GameContents(name: '육삼 _ _', index: '51'),
  GameContents(name: '아이 _ _', index: '52'),
  GameContents(name: '부루 _ _', index: '53'),
  GameContents(name: '메타 _ _', index: '54'),
  GameContents(name: '포토 _ _', index: '55'),
  GameContents(name: '블루 _ _', index: '56'),
  GameContents(name: '마스 _ _', index: '57'),
  GameContents(name: '장기 _ _', index: '58'),
  GameContents(name: '장래 _ _', index: '59'),
  GameContents(name: '개과 _ _', index: '60'),
  GameContents(name: '내로 _ _', index: '61'),
  GameContents(name: '슈퍼 _ _', index: '62'),
  GameContents(name: '르세 _ _', index: '63'),
  GameContents(name: '아이 _ _', index: '64'),
  GameContents(name: '손목 _ _', index: '65'),
  GameContents(name: '스핑 _ _', index: '66'),
  GameContents(name: '봅슬 _ _', index: '67'),
  GameContents(name: '보디 _ _', index: '68'),
  GameContents(name: '비상 _ _', index: '69'),
  GameContents(name: '게이 _ _', index: '70'),
  GameContents(name: '오토 _ _', index: '71'),
  GameContents(name: '강강 _ _', index: '72'),
  GameContents(name: '타임 _ _', index: '73'),
  GameContents(name: '콩쥐 _ _', index: '74'),
  GameContents(name: '유체 _ _', index: '75'),
  GameContents(name: '납작 _ _', index: '76'),
  GameContents(name: '회전 _ _', index: '77'),
  GameContents(name: '먹이 _ _', index: '78'),
  GameContents(name: '아프 _ _', index: '79'),
];

final List<GameContents> tele = [
  GameContents(name: '가', index: '1'),
  GameContents(name: '다', index: '2'),
  GameContents(name: '나', index: '3'),
  GameContents(name: '물', index: '4'),
  GameContents(name: '자', index: '5'),
  GameContents(name: '우', index: '6'),
  GameContents(name: '하', index: '7'),
  GameContents(name: '기', index: '8'),
  GameContents(name: '이', index: '9'),
  GameContents(name: '산', index: '10'),
  GameContents(name: '시', index: '11'),
  GameContents(name: '아', index: '12'),
  GameContents(name: '화', index: '13'),
  GameContents(name: '마', index: '14'),
  GameContents(name: '조', index: '15'),
  GameContents(name: '모', index: '16'),
  GameContents(name: '도', index: '17'),
  GameContents(name: '라', index: '18'),
  GameContents(name: '호', index: '19'),
  GameContents(name: '이', index: '20'),
  GameContents(name: '레', index: '21'),
  GameContents(name: '내', index: '22'),
  GameContents(name: '네', index: '23'),
  GameContents(name: '사', index: '24'),
  GameContents(name: '감', index: '25'),
  GameContents(name: '기', index: '26'),
  GameContents(name: '가', index: '27'),
  GameContents(name: '아', index: '28'),
  GameContents(name: '마', index: '29'),
  GameContents(name: '이', index: '30'),
  GameContents(name: '중', index: '31'),
  GameContents(name: '미', index: '32'),
  GameContents(name: '일', index: '33'),
  GameContents(name: '우', index: '34'),
  GameContents(name: '자', index: '35'),
  GameContents(name: '라', index: '36'),
  GameContents(name: '나', index: '37'),
  GameContents(name: '모', index: '38'),
  GameContents(name: '인', index: '39'),
  GameContents(name: '민', index: '40'),
  GameContents(name: '지', index: '41'),
  GameContents(name: '물', index: '42'),
  GameContents(name: '불', index: '43'),
  GameContents(name: '산', index: '44'),
  GameContents(name: '거', index: '45'),
  GameContents(name: '토', index: '46'),
  GameContents(name: '월', index: '47'),
  GameContents(name: '나', index: '48'),
  GameContents(name: '구', index: '49'),
  GameContents(name: '원', index: '50'),
];

final List<GameContents> telestration = [
  GameContents(name: '스컹크', index: '1'),
  GameContents(name: '쿼카', index: '2'),
  GameContents(name: '엑스레이', index: '3'),
  GameContents(name: '번지점프', index: '4'),
  GameContents(name: '통나무집', index: '5'),
  GameContents(name: '공중전화', index: '6'),
  GameContents(name: '해외직구', index: '7'),
  GameContents(name: '미키마우스', index: '8'),
  GameContents(name: '찰리채플린', index: '9'),
  GameContents(name: '수족관', index: '10'),
  GameContents(name: '에펠탑', index: '11'),
  GameContents(name: '개미핥기', index: '12'),
  GameContents(name: '에어로빅', index: '13'),
  GameContents(name: '필라테스', index: '14'),
  GameContents(name: '합창단', index: '15'),
  GameContents(name: '어부', index: '16'),
  GameContents(name: '허수아비', index: '17'),
  GameContents(name: '치과의사', index: '18'),
  GameContents(name: '암벽등반', index: '19'),
  GameContents(name: '개그맨', index: '20'),
  GameContents(name: '경찰서', index: '21'),
  GameContents(name: '판사', index: '22'),
  GameContents(name: '연필깎이', index: '23'),
  GameContents(name: '타코야끼', index: '24'),
  GameContents(name: '금붕어', index: '25'),
  GameContents(name: '구미호', index: '26'),
  GameContents(name: '제빵사', index: '27'),
  GameContents(name: '평양냉면', index: '28'),
  GameContents(name: '크루아상', index: '29'),
  GameContents(name: '물개', index: '30'),
  GameContents(name: '티라노사우루스', index: '31'),
  GameContents(name: '우주정거장', index: '32'),
  GameContents(name: '서예', index: '33'),
  GameContents(name: '주먹도끼', index: '34'),
  GameContents(name: '빗살무늬토기', index: '35'),
  GameContents(name: '면접', index: '36'),
  GameContents(name: '야근', index: '37'),
  GameContents(name: '삼계탕', index: '38'),
  GameContents(name: '이순신장군', index: '39'),
  GameContents(name: '감자탕', index: '40'),
  GameContents(name: '낙동강', index: '41'),
  GameContents(name: '연어', index: '42'),
  GameContents(name: '다이빙', index: '43'),
  GameContents(name: '고구려', index: '44'),
  GameContents(name: '선생님', index: '45'),
  GameContents(name: '경전철', index: '46'),
  GameContents(name: '물회', index: '47'),
  GameContents(name: '디자이너', index: '48'),
  GameContents(name: '미역', index: '49'),
  GameContents(name: '북극곰', index: '50'),
  GameContents(name: '정전기', index: '51'),
  GameContents(name: '솜사탕', index: '52'),
  GameContents(name: '면도크림', index: '53'),
  GameContents(name: '독수리', index: '54'),
  GameContents(name: '콧노래', index: '55'),
  GameContents(name: '좀비', index: '56'),
  GameContents(name: '비누', index: '57'),
  GameContents(name: '셜록홈즈', index: '58'),
  GameContents(name: '엽서', index: '59'),
  GameContents(name: '조각 케이크', index: '60'),
  GameContents(name: '축제', index: '61'),
  GameContents(name: '구호', index: '62'),
  GameContents(name: '하프', index: '63'),
  GameContents(name: '__<-진행자 맘대로', index: '64'),
  GameContents(name: '연필깍이', index: '65'),
  GameContents(name: '페디큐어', index: '66'),
  GameContents(name: '번지점프', index: '67'),
  GameContents(name: '당구장', index: '68'),
  GameContents(name: '카지노', index: '69'),
  GameContents(name: '미역국', index: '70'),
  GameContents(name: '외발자전거', index: '71'),
  GameContents(name: '탁구', index: '72'),
  GameContents(name: '도서관', index: '73'),
  GameContents(name: '도서관', index: '74'),
  GameContents(name: '밥도둑', index: '75'),
  GameContents(name: '중고차', index: '76'),
  GameContents(name: '추석', index: '77'),
  GameContents(name: '다람쥐', index: '78'),
  GameContents(name: '애벌레', index: '79'),
  GameContents(name: '두꺼비', index: '80'),
  GameContents(name: '고구마', index: '81'),
  GameContents(name: '스파게티', index: '82'),
  GameContents(name: '판다', index: '83'),
  GameContents(name: '놀이터', index: '84'),
  GameContents(name: '팝콘', index: '85'),
  GameContents(name: '겁쟁이', index: '86'),
  GameContents(name: '초밥', index: '87'),
  GameContents(name: '해적', index: '88'),
  GameContents(name: '스누피', index: '89'),
  GameContents(name: '닭다리', index: '90'),
  GameContents(name: '치킨', index: '91'),
  GameContents(name: '편의점', index: '92'),
  GameContents(name: '고무줄', index: '93'),
  GameContents(name: '스노우보드', index: '94'),
  GameContents(name: '돈까스', index: '95'),
  GameContents(name: '각시탈', index: '96'),
  GameContents(name: '남산타워', index: '97'),
  GameContents(name: '백화점', index: '98'),
  GameContents(name: '화산', index: '99'),
];

final List<GameContents> music1990 = [
  GameContents(name: 'ㄴㅂ - ㅈㅇㅍ', answer: '나비 - 조용필', index: '1'),
  GameContents(name: 'ㅅㄹㅎㅇ - ㄱㅇㅅ', answer: '사랑해요 - 김완선', index: '2'),
  GameContents(
      name: 'ㅅㄹㅇ ㅇㅅㅇ \nㅇㅇㄷㅁ - ㅇㅈㅂ', answer: '사랑에\n연습이 있었다면 - 임재범', index: '3'),
  GameContents(name: 'ㄴ ㅇㅇㅇ \n- ㅅㅌㅈ', answer: '난 알아요 - 서태지', index: '4'),
  GameContents(
      name: 'ㄱ ㅈㅇ ㄱㄷㄹ\n ㅁㄴ - ㅇㅅㅎ', answer: '그 중에 그대를 \n 만나 - 이선희', index: '5'),
  GameContents(name: 'ㅎㅂㄹㄱ - ㅎㄷㅈ', answer: '해바라기 - 한동준', index: '6'),
  GameContents(name: 'ㅈㅁㄷ ㅁㄴ\n- ㄱㄱㅁ', answer: '잘못된 만남\n- 김건모', index: '7'),
  GameContents(
      name: 'ㄱㄹ ㅅㄹ ㄸ\nㅇㅅㄴㅅ - ㄷㄷ', answer: '그런 사람 또\n없습니다 - 더더', index: '8'),
  GameContents(name: 'ㅁㄹㅅㄱ\n- ㄷ ㅋㄹㅅ', answer: '모래시계\n- 더 클래식', index: '9'),
  GameContents(name: 'ㅇㅇㄴ - ㅈㅎㅈ ', answer: '잊었니 - 장혜진', index: '10'),
  GameContents(name: 'ㄴㅈ ㅁㅎㅊㄹ\n- ㄹㄹ', answer: '남자 만화처럼\n- 룰라', index: '11'),
  GameContents(
      name: 'ㄴㄹ ㅍㅇ ㅇㅇㅁ\n- ㄱㅎㅅ', answer: '너를 품에 안으면\n- 김현식', index: '12'),
  GameContents(
      name: 'ㄴㅇㄱㄹ ㄸ\nㄱㄱ ㅅㅇ\n- ㅇㅈㅅ',
      answer: '너에게로 또\n가고 싶어\n- 이정석',
      index: '13'),
  GameContents(name: 'ㅂㄲ ㅇㄷ\n- ㅅㅂㅊ', answer: '벚꽃 엔딩\n- 소방차', index: '14'),
  GameContents(
      name: 'ㄴ ㅇㅇㅇ ㄱㅂㅇ\n- ㄱㅅㅎ', answer: '내 이름은 권보아\n- 김수희', index: '15'),
  GameContents(name: 'ㄷ ㅅ ㅁㅇ\n- ㅇㅂㅈㅋㅍ', answer: '두 손 모아\n- 어반자카파', index: '16'),
  GameContents(
      name: 'ㅇㄹ ㅇㅂㅎㄷ\nㅈㄱㅈ - ㅇㅌㅇ', answer: '우리 이별했던\n정거장- 원타임', index: '17'),
  GameContents(name: 'ㅅㄹㅇㅃㅇ\n- ㅇㅈㅎ', answer: '사랑일뿐야\n- 엄정화', index: '18'),
  GameContents(name: 'ㄴㅇㄱㄹ ㄸ\nㄱㄱ ㅅㅇ', answer: '너에게로 또\n가고 싶어', index: '19'),
  GameContents(name: 'ㄴㅁㅇ - ㅎㄷㅈ', answer: '너만이 - 한동준', index: '20'),
  GameContents(name: 'ㅊㅎ\n- ㅂㅇㄹㄱㅇㄱㅇ', answer: '청혼\n- 봄여름가을겨울', index: '21'),
  GameContents(name: 'ㅇㅈㅊㄹ - ㄱㄱㅎ', answer: '어제처럼 - 김경호', index: '22'),
  GameContents(name: 'ㅎㅎㅎㅆ - ㅈㅇㄹ', answer: '하하하쏭 - 자우림', index: '23'),
  GameContents(name: 'ㅂㅅ - ㅈㅅ', answer: '비상 - 조선', index: '24'),
  GameContents(name: 'ㄱㅇ ㅅㅇ ㅁㅅ\n- ㄱㅇㅅ', answer: '기억 속의 미소\n- 김완선', index: '25'),
  GameContents(name: 'ㅇㅂㅈ - ㅇㅅㄱ', answer: '아버지 - 이승기', index: '26'),
  GameContents(name: 'ㅊㅇ ㄱ ㄴㄲㅊㄹ\n- ㄹ', answer: '처음 그 느낌처럼\n- 린', index: '27'),
  GameContents(
      name: 'ㅇㅇㅇ ㅎㄷㄴ\nㅁㅇㅇㄹ\n-  ㄱㄱㅁ',
      answer: '잊어야 한다는\n마음으로\n- 김건모',
      index: '28'),
  GameContents(name: 'ㅇㅅㅎ ㅇㅎ - ㅋ', answer: '이상한 여행 - 쿨', index: '29'),
  GameContents(name: 'ㅎㅇ\n- ㅇㄷㅎㅂㄷ', answer: '희야\n- 윤도현밴드', index: '30'),
  GameContents(
      name: 'ㅇㅂㅇ ㅈㄴㅁ\n- ㅅㅌㅈㅇ ㅇㅇㄷ', answer: '이밤이 지나면\n- 서태지와 아이들', index: '31'),
  GameContents(name: 'ㅂㄱㅂㄱ - ㅈㅅㅁ', answer: '빙글빙글 - 조성모', index: '32'),
  GameContents(
      name: 'ㅂㄹㅇ ㅂㅇㅇㅁ\nㅈㄱㅇ\n- ㅇㄷㅎㅂㄷ',
      answer: '바람이 불었으면\n좋겠어\n- 윤도현밴드',
      index: '33'),
  GameContents(name: 'ㅁㄴ ㅋㅍ\n- ㄱㅁㅈ', answer: '모닝 커피\n- 김민종', index: '34'),
  GameContents(
      name: 'ㄱㅅ ㅇㄷㅇ\n- ㅅㅌㅈㅇ ㅇㅇㄷ', answer: '교실 이데아\n- 서태지와 아이들', index: '35'),
  GameContents(name: 'ㅇㄸㄱㅇ\n- ㅈㅎㅈ', answer: '어떤가요\n- 장혜진', index: '36'),
  GameContents(name: 'ㅂㄹㅇ ㄴㄹ\n- ㄱㅎㄹ', answer: '바람의 노래\n- 김학래', index: '37'),
  GameContents(name: 'ㄴ ㅇㄹㅈ ㄲ\n- ㅌㅂ', answer: '나 어릴적 꿈\n- 터보', index: '38'),
  GameContents(name: 'ㅇㄷㅇ\n- ㅈㅁㅇㄱ', answer: '안돼요\n- 장미여관', index: '39'),
  GameContents(name: 'ㅈㄴ - ㅇㅈㅅ', answer: '자니 - 이정석', index: '40'),
  GameContents(
      name: 'ㅇㄸㄱ ㅅㄹㅇ\nㄱㄹㅇ - ㅎㅌㅈ', answer: '어떻게 사랑이\n그래요 - 황태지', index: '41'),
  GameContents(
      name: 'ㅇㅂ ㄱㄹㄱ ㅁㄹ\n- ㅂㅁㄱ', answer: '이별 그리고 미련\n- 박미경', index: '42'),
  GameContents(
      name: 'ㅁㅂㅇ ㅊㅊ\n- ㅅㅌㅈㅇ ㅇㅇㄷ', answer: '맨발의 청춘\n- 서태지와 아이들', index: '43'),
  GameContents(
      name: 'ㄱ ㄴㅈ ㄱ ㅇㅈ\n- ㅇㅁㅅ', answer: '그 남자 그 여자\n- 이문세', index: '44'),
  GameContents(name: 'ㅂㄹㄱㅇ ㅅㅇ\n- ㅈㅇㅍ', answer: '바람결에 실어\n- 조용필', index: '45'),
  GameContents(name: 'ㅅㄹㅎㅈㅁ\n- ㅇㅅㅎ', answer: '사랑했지만\n- 이승환', index: '46'),
  GameContents(name: 'ㄴㄴ ㅇㄹㅇ\n- ㅋ', answer: '나는 외로워\n- 쿨', index: '47'),
  GameContents(name: 'ㄷㅈ\n- ㄷ ㅋㄹㅅ', answer: '답장\n- 더 클래식', index: '48'),
  GameContents(name: 'ㅁㅎㅈ ㅁ\n- ㅈㅅ', answer: '말하지 마\n- 조선', index: '49'),
  GameContents(name: 'ㅅㄹㅎ ㅎㅇ\n- ㄱㅁㅇ', answer: '사랑한 후에\n- 김민우', index: '50'),
  GameContents(name: 'ㄴㅅㄹ ㄴㄱㅇ - ㄱㅎㅅ', answer: '내사랑 내곁에 - 김현식', index: '51'),
  GameContents(name: 'ㄴㄹ ㅅㄹㅎ - ㅎㄷㅈ', answer: '너를 사랑해 - 한동준', index: '52'),
  GameContents(
      name: 'ㄷㅅ ㅁㄴ ㄴㅇㄱ - ㅍㄴㅋㅇ', answer: '다시 만난 너에게 - 피노키오', index: '53'),
  GameContents(name: 'ㄴㅇ ㄴㄹ - ㄱㄱㅅ', answer: '나의 노래 - 김광석', index: '54'),
  GameContents(
      name: 'ㅇㅈ ㅇㄹㄷ ㅇㅇㄷ - ㄱㅇㅇㅂ', answer: '아주 오래된 연인들 - ㄱㅇㅇㅂ', index: '55'),
  GameContents(name: 'ㅇㅂㅇ ㄱㄴ - ㅇㅅ', answer: '이별의 그늘 - 윤상', index: '56'),
  GameContents(name: 'ㄴㄱ - ㅇㅅㅎ', answer: '내게 - 이승환', index: '57'),
  GameContents(name: 'ㅍㅇㅈ - ㅇㅈㅎ', answer: '포이즌 - 엄정화', index: '58'),
  GameContents(name: 'ㄴㄱ ㅁㅇ - ㅇㅊㅎ', answer: '내가 만일 - 안치환', index: '59'),
  GameContents(name: 'ㄷㅅㅇ - ㄴㄱㅌ', answer: '도시인 - 넥스트', index: '60'),
  GameContents(name: 'ㅇㅁ - ㄱㅅㅎ', answer: '애모 - 김수희', index: '61'),
  GameContents(name: 'ㄴㄹ ㅎㅎ ㅁㅇ - ㅇㅅㅎ', answer: '너를 향한 마음 - 이승환', index: '62'),
  GameContents(
      name: 'ㅇ ㅂㅇ ㅈㄴㄷㄹ - ㅍㄹ ㅎㄴ', answer: '이 밤이 지나도록 - 푸른 하늘', index: '63'),
  GameContents(name: 'ㅎㅁㅅㅎ - ㅂㅈㅅ', answer: '희망사항 - 변진섭', index: '64'),
  GameContents(name: 'ㄴㄷㄹ - ㄱㅎㅅ', answer: '넋두리 - 김현식', index: '65'),
  GameContents(name: 'ㅍㄱ - ㄱㄱㅁ', answer: '핑계 - 김건모', index: '66'),
  GameContents(name: 'ㅅ ㅇㄹㅇ ㅅㄹ - ㄱㅇㅇㅂ', answer: '신 인류의 사랑 - ㄱㅇㅇㅂ', index: '67'),
  GameContents(name: 'ㅅㄹㅇ ㅇㅎㅇ - ㄱㅈㅎ', answer: '사랑을 위하여 - 김종환', index: '68'),
  GameContents(
      name: 'ㄴㅇㄱ ㄷㄹㅈㄱ ㅅㅇ ㅇㅇㄱ - ㄱㅇㅇㅂ',
      answer: '너에게 들려주고 싶은 이야기 - ㄱㅇㅇㅂ',
      index: '69'),
  GameContents(name: 'ㅇㄹㅊㅇ ㅂ - ㅎㅂㅊ', answer: '유리창엔 비 - 햇빛촌', index: '70'),
  GameContents(name: 'ㄷㅍㅇ - ㅍㄴ', answer: '달팽이 - 패닉', index: '71'),
  GameContents(
      name: 'ㅅㅊ ㅇ ㅈㅎㅊ ㅇㅇㅅ - ㄷㅁㅇ', answer: '시청 앞 지하철 역에서 - 동물원', index: '72'),
  GameContents(
      name: 'ㄲㅇㅅ ㅂ ㄱㄹ - ㅍㄹ ㅎㄴ', answer: '꿈에서 본 거리 - 푸른 하늘', index: '73'),
  GameContents(name: 'ㅅㄹㅎㅅㄹ - ㅂㅎ', answer: '사랑할수록 - 부활', index: '74'),
  GameContents(name: 'ㄷㅇ ㅁㄹ - ㄱㅎㅊ', answer: '달의 몰락 - 김현철', index: '75'),
  GameContents(name: 'ㄱㅇㅇ ㅅㅈ - ㅈㄹㅎ', answer: '기억의 습작 - 전람회', index: '76'),
  GameContents(
      name: 'ㅁㅅ ㅅㅇ ㅂㅊ ㄱㄷ - ㅅㅅㅎ', answer: '미소 속에 비친 그대 - 신승훈', index: '77'),
  GameContents(
      name: 'ㄴㄹ ㅅㅍㄱ ㅎㄴ ㅅㄹㄷ - ㄱㄱㅎ', answer: '나를 슬프게 하는 사람들 - 김경호', index: '78'),
  GameContents(
      name: 'ㄸ ㄷㄹ ㅁㄴㅇ ㅇㅎ - ㄱㅁㅈ', answer: '또 다른 만남을 위해 - 김민종', index: '79'),
  GameContents(name: 'ㄱ ㅎㄹ ㅇㄹㄷㅇ - ㅅㅅㅎ', answer: '그 후로 오랫동안 - 신승훈', index: '80'),
  GameContents(
      name: 'ㄷㅅㄴ ㅇㄷ ㅇㄴㅇ - ㅇㅅㄱ', answer: '당신은 어디 있나요 - 양수경', index: '81'),
  GameContents(name: 'ㅂㅇㄴ ㄴ ㅅㅊㅎ - ㄱㅎㅅ', answer: '비오는 날 수채화 - 김현식', index: '82'),
  GameContents(name: 'ㅇㅈㄴ ㄱ ㅈㄹㅇ - ㅅㅎㅂ', answer: '언제나 그 자리에 - 신효범', index: '83'),
  GameContents(name: 'ㅅㄹㅇ ㅎㄲㅇ - ㄴㅅㅈㄷ', answer: '사랑을 할꺼야 - 녹색지대', index: '84'),
  GameContents(name: 'ㅇㄹㅈ ㄱㄴ - ㅇㅈㅅ', answer: '오래전 그날 - 윤종신', index: '85'),
  GameContents(name: 'ㅁㅈㅇ ㅋㅅㅌ - ㅇㅅㅊ', answer: '마지막 콘서트 - 이승철', index: '86'),
  GameContents(name: 'ㅂㄱㅅㅇ ㅇㄱ - ㅁㅎㄱ', answer: '보고싶은 얼굴 - 민해경', index: '87'),
  GameContents(name: 'ㄴ ㅎ ㅅ ㅇㅇ - ㄱㅅㅇ', answer: '넌 할 수 있어 - 강산에', index: '88'),
  GameContents(
      name: 'ㄱㄷㅍㅇ ㅈㄷㅇㅇㅁ - ㅂㅈㅅ', answer: '그대품에 잠들었으면 - 박정수', index: '89'),
  GameContents(name: 'ㅂㅎ - ㅇㅅㅊ', answer: '방황 - 이승철', index: '90'),
  GameContents(name: 'ㄴㄹ ㅅㄹㅎㄱㄷ - ㅈㅇㄴ', answer: '너를 사랑하고도 - 전유나', index: '91'),
  GameContents(name: 'ㄴㅇ ㄱㅎㅅ - ㅇㅈㅅ', answer: '너의 결혼식 - 윤종신', index: '92'),
  GameContents(
      name: 'ㅇ ㅂㅇ ㄲㅇ ㅈㄱ - ㅅㄹㄷ', answer: '이 밤의 끝을 잡고 - 솔리드', index: '93'),
  GameContents(name: 'ㅁㅂㅇ ㅅ - ㄷ ㅋㄹㅅ', answer: '마법의 성 - 더 클래식', index: '94'),
  GameContents(name: 'ㅁㅈㄱ ㄷㅇ - ㅇㅇㅅ', answer: '먼지가 되어 - 이윤수', index: '95'),
  GameContents(name: 'ㄴ ㅎㅍㅎ - ㅇㅅㄹ', answer: '난 행복해 - 이소라', index: '96'),
  GameContents(name: 'ㅇㄴ ㄱㅇ ㅂㅇㅁ - ㅂㅈㅇ', answer: '오늘 같은 밤이면 - 박정운', index: '97'),
  GameContents(name: 'ㅂㅇㅈ ㅇㄴ ㅅㄹ - ㅅㅅㅎ', answer: '보이지 않는 사랑 - 신승훈', index: '98'),
  GameContents(
      name: 'ㄱㄷㅇㅇ ㅂㄹ - ㄱㅎㅊ, ㅇㅅㄹ', answer: '그대안의 블루 - 김현철, 이소라', index: '99'),
];
final List<GameContents> music2000 = [
  GameContents(name: 'ㅈㅈ\n- ㅂㄹㅇ ㅇㅇㅈ', answer: '점점\n- 브라운 아이즈', index: '1'),
  GameContents(name: 'ㄴㅇ ㄲ - ㅂㅎㅅ', answer: '눈의 꽃 - 박효신', index: '2'),
  GameContents(name: 'ㅅㄹㅎㄴㅂ\n- ㅇㄷㅎ', answer: '사랑했나봐\n- 윤도현', index: '3'),
  GameContents(name: 'ㅁㅈㅁ ㅇㅅ - ㅂㅂ', answer: '마지막 인사 - 빅뱅', index: '4'),
  GameContents(name: 'ㅎㄹ ㅎㄹ - ㅂㅂ', answer: '하루 하루 - 빅뱅', index: '5'),
  GameContents(
      name: 'ㅅㄹ ㅇㅇ\n- ㅇㅍㅌ ㅇㅇㄹㄷ', answer: '사랑 앓이\n- FT아일랜드', index: '6'),
  GameContents(name: 'ㅊㄱㅇ - ㅇㅅㅇ', answer: '친구여 - 인순이', index: '7'),
  GameContents(name: 'ㄱㅅ - ㄱㄷㄹ', answer: '감사 - 김동률', index: '8'),
  GameContents(
      name: 'ㅎㅈ ㅅ ㅇㄴ ㅇ\n- ㅂㅎㅅ', answer: '해줄 수 없는 일 \n- 박효신', index: '9'),
  GameContents(name: 'ㄱㅈㅁ - ㅂㅂ', answer: '거짓말 - 빅뱅', index: '10'),
  GameContents(name: 'ㅊㅁㅇㄱㅊㄹ\n- ㅂㅈㅇ', answer: '총맞은것처럼\n- 백지영', index: '11'),
  GameContents(name: 'ㄴ ㄴㄹ ㅅㄹㅎ\n- ㅅㅎㅂ', answer: '난 너를 사랑해\n- 신효범', index: '12'),
  GameContents(name: 'ㄱㄷㄱ ㅂㄷ\n- ㅇㅅㅊ', answer: '그대가 분다\n- ㅇㅅㅊ', index: '13'),
  GameContents(name: 'ㄴㅅㄹ\n- ㅇㅅㅈ ㅇㄴㅂ', answer: '내사람- 에스지워너비', index: '14'),
  GameContents(name: 'ㅅㅋㅅ\n- ㅇㅆㅁ', answer: '서커스\n- 엠씨몽', index: '15'),
  GameContents(
      name: 'ㄴㄱ ㅇㄴㄱ\nㅇㄴㅇ - ㄹㅆ', answer: '내가 웃는게\n아니야 - 리쌍', index: '16'),
  GameContents(name: 'ㅌㅁ - ㅇㄷㄱㅅ', answer: '텔미 - 원더걸스', index: '17'),
  GameContents(
      name: 'ㅅㅇㅇ ㅁㅎㅂ \n- ㅅㄴㅅㄷ', answer: '소원을 말해봐\n- 소녀시대', index: '18'),
  GameContents(
      name: 'ㅂㅆ ㅇㄴ\n- ㅂㄹㅇ ㅇㅇㅈ', answer: '벌써 일년\n- 브라운아이즈', index: '19'),
  GameContents(
      name: 'ㄷㅅ ㅅㄹㅎㄷ\nㅁㅎㄲ - ㄱㄷㄹ', answer: '다시 사랑한다\n말할까 - 김동률', index: '20'),
  GameContents(name: 'ㄴㄱ ㅇㄴ ㄱ\n- ㅅㅅㄱ', answer: '내게 오는 길\n- 성시경', index: '21'),
  GameContents(name: 'ㅇㄹㅎ - ㅋ', answer: '아로하 - 쿨', index: '22'),
  GameContents(name: 'ㄴㅁㄱㅇㅇ\n- ㅊㄹㅍㅌ', answer: '낭만고양이\n- 체리필터', index: '23'),
  GameContents(name: 'ㅂㅁ - ㅋㅇㅌ', answer: '비몽\n- 코요태', index: '24'),
  GameContents(name: 'ㅇㅌㄹㅌㅅ ㅅㄴ\n- ㅂㅇ', answer: '아틀란티스 소녀\n- 보아', index: '25'),
  GameContents(name: 'ㅊㄴ - ㅂㅁㅁ', answer: '체념 - 빅마마', index: '26'),
  GameContents(name: 'ㄱㅎㅁ ㅇㄱ\n- ㅇㅅㅇ', answer: '광화문 연가\n- 이수영', index: '27'),
  GameContents(name: 'ㅂㅊㅂ - ㅎㅅ', answer: '불치병 - 휘성', index: '28'),
  GameContents(name: 'ㅈㅇ ㅅㄹ\n- ㅂㅎㅅ', answer: '좋은 사람\n- 박효신', index: '29'),
  GameContents(name: 'ㄱㅅ - ㅂㅈ', answer: '가시 - 버즈', index: '30'),
  GameContents(
      name: 'ㄴㅇㄱㄹ ㄸㄴㄴ ㅇㅎ - ㅂㅈ', answer: '나에게로 떠나는 여행 -버즈', index: '31'),
  GameContents(name: 'ㅅㄹㅅㄹㅇ\n- ㄱㅈㄱ', answer: '사랑스러워\n- 김종국', index: '32'),
  GameContents(name: 'ㅌㅇㅇ ㅍㅎㄴ\nㅂㅂ - ㅂ', answer: '태양을 피하는\n방법 - 비', index: '33'),
  GameContents(name: 'ㅈㄴ\n- ㅍㄹㅇㅁㄹ', answer: '자니\n- 프라이머리', index: '34'),
  GameContents(name: 'ㅁㅇㅇ - ㅌㅇ', answer: ' 만약에 - 태연', index: '35'),
  GameContents(name: 'ㅅㄹ ㅇㅎ\n- ㅂㅈㅇ', answer: '사랑 안해\n- 백지영', index: '36'),
  GameContents(name: 'ㄴㅈㄹ ㅁㄹ\n- ㅂㅈ', answer: '남자를 몰라\n- 버즈', index: '37'),
  GameContents(name: 'ㄱㄹㅇㅅ\n- ㅅㅅㄱ', answer: '거리에서\n- 성시경', index: '38'),
  GameContents(name: 'ㅂㅎㄱ - ㄱㅂㅇ', answer: '비행기 - 거북이', index: '39'),
  GameContents(name: 'ㅈㅅㄹ - ㄷ ㄴㅊ', answer: '잔소리 - 더 넛츠', index: '40'),
  GameContents(
      name: 'ㅊㅇㅇ ㅅㄹㅇ\nㄷㅇ - ㅂㅎㅅ', answer: '추억은 사랑을\n닮아 - 박효신', index: '41'),
  GameContents(name: 'ㅈㅇ ㄴ\n- ㄷㅇㄴㅁ ㄷㅇ', answer: '죽일 놈\n- 다이나믹 듀오', index: '42'),
  GameContents(name: 'ㄲㅇ - ㅂㅈㅎ', answer: '꿈에 - 박정현', index: '43'),
  GameContents(name: 'ㅎㅈㅇ ㄱㅊㄱ\n- ㅇㅅ', answer: '화장을 고치고\n- 왁스', index: '44'),
  GameContents(name: 'ㄱㅇ ㅂㄱ - ㅌㅇ', answer: '같은 베개 - 테이', index: '45'),
  GameContents(name: 'ㅅㄱㅈ - ㅇㅌㅇ', answer: '세글자 - 엠투엠', index: '46'),
  GameContents(name: 'ㄹㄷㄷ - ㅅㅇㄴ', answer: '링딩동 - 샤이니', index: '47'),
  GameContents(name: 'ㅇㅂㄹㅋㅌㅂㄹ\n- ㅂㅇㄱ', answer: '아브라카타브라\n- 브아걸', index: '48'),
  GameContents(name: 'ㅎㅇㅅ - ㅍㅁㄴ', answer: '핫이슈 - 포미닛', index: '49'),
  GameContents(name: 'ㄴㅂㄷ - ㅇㄷㄱㅅ', answer: '노바디 - 원더걸스', index: '50'),
  GameContents(name: 'ㅅㄹㅇ ㅅ\n- ㅇㅆㄷㅁㅅ', answer: '사랑의 시\n- 엠씨더맥스', index: '51'),
  GameContents(name: 'ㅆㅎ - ㅇㄷㄱㅅ', answer: '쏘핫 - 원더걸스', index: '52'),
  GameContents(name: 'ㅇㅅㄴㅇ - ㅈㅅㅁ', answer: '아시나요 - 조성모', index: '53'),
  GameContents(
      name: 'ㅇㄹㄴ ㅈㅂ ㅈ\nㅇㅇㄹㅇ - ㅅㅅㄱ', answer: '우린 제법 잘\n어울려요 - 성시경', index: '54'),
  GameContents(name: 'ㄴㅂ ㅇㄷ ㅅㅌㄹ\n- ㅂㅎ', answer: '네버 엔딩 스토리\n- 부활', index: '55'),
  GameContents(name: 'ㅁㅇㅎㅇ - ㄱㄱㅁ', answer: '미안해요 - 김건모', index: '56'),
  GameContents(name: 'ㅈㅈㄹ ㄱㅇ\n- ㄱㅈㄱ', answer: '제자리 걸음\n- 김종국', index: '57'),
  GameContents(name: 'ㅇㅈ - ㅅㅂ', answer: '열정 - 세븐', index: '58'),
  GameContents(
      name: 'ㅅㄹㅎㄷ ㅎㅈ ㅅ\nㅇㄷㅁ - ㅅㅅㅎ',
      answer: '사랑해도 헤질 수\n있다면 - 신승훈',
      index: '59'),
  GameContents(name: 'ㅅㄹㅇㅇ\n- ㅇㅇㅍ ㅇㅇㄹㄷ', answer: '사랑앓이\n- FT아일랜드', index: '60'),
  GameContents(name: 'ㅅㄹ ㄱㄱ\nㅁㄷ - ㅇㅍ', answer: '사랑 그게\n뭔데 - 양파', index: '61'),
  GameContents(
      name: 'ㅈㅁ ㅅㄹㅎㅇㄲ\n- ㅂㄹㅇ ㅇㅇㄷ ㅅㅇ',
      answer: '정말 사랑했을까\n- 브라운 아이드 소울',
      index: '62'),
  GameContents(name: 'ㅈㅇㅂ\n- ㅇㅅㅈ ㅇㄴㅂ', answer: '죄와벌\n- 에스지워너비', index: '63'),
  GameContents(name: 'ㅁㅇ - ㅇㄱㅊ', answer: '미인 - 이기찬', index: '64'),
  GameContents(name: 'ㅇㄱㅁ - ㅇㅇㅂ', answer: '이거면 - 아이비', index: '65'),
  GameContents(
      name: 'ㅅㄹㅇ ㅎㄱㄹ\nㄴㄱㄱ - ㅌㅇ', answer: '사랑은 향기를\n남기고 - 테이', index: '66'),
  GameContents(
      name: 'ㄸ ㅎ ㅂ ㅅㄹㅇ\nㄱㄱ - ㅇㄱㅊ', answer: '또 한 번 사랑은\n가고 - 이기찬', index: '67'),
  GameContents(name: 'ㅎㄱ ㅎㄷ ㅁ\n- ㅇㅅㄱ', answer: '하기 힘든 말\n- 이승기', index: '68'),
  GameContents(name: 'ㄹㄹㅍ\n- ㅂㅂ, ㅌㅇㄴㅇ', answer: '롤리팝\n- 빅뱅, 투애니원', index: '69'),
  GameContents(
      name: 'ㅅㄹㅇ ㄱㅅㅇ\nㅅㅋㄷ - ㅂㅈ', answer: '사랑은 가슴이\n시킨다 - 버즈', index: '70'),
  GameContents(name: 'ㅊㄹ - ㅋㄴ', answer: '초련 - 클론', index: '71'),
  GameContents(name: 'ㅁㄱㅇㅅ - ㅂㅎㅅ', answer: '먼곳에서 - 박효신', index: '72'),
  GameContents(name: 'ㄱㅅㄴㅁ - ㅈㅅㅁ', answer: '가시나무 - 조성모', index: '73'),
  GameContents(name: 'ㄱㅎㅇ ㅎ\nㄱㄹㅁ - ㅋ', answer: '결혼을 할\n거라면 - 쿨', index: '74'),
  GameContents(name: 'ㄴㅇ ㅇㅇ\n- ㅇㅊㅈ', answer: '나의 연인\n- 임창정', index: '75'),
  GameContents(name: 'ㅁ - ㄱㅎㅈ', answer: '멍 - 김현정', index: '76'),
  GameContents(name: 'ㅌㅁㄴ - ㅇㅎㄹ', answer: '텐미닛 - 이효리', index: '77'),
  GameContents(name: 'ㅊㅊㅈ - ㄱㄱㅁ', answer: '청첩장 - 김건모', index: '78'),
  GameContents(name: 'ㄷㅅㅇ ㅁㄹㅅㄱㅇ\n- ㅍㅋ', answer: '당신은 모르실거야\n- 핑클', index: '79'),
  GameContents(name: 'ㅎㄹㄹ - ㅇㅅㅇ', answer: '휠릴리 - 이수영', index: '80'),
  GameContents(
      name: 'ㄱ ㄴㅈ ㄱ ㅇㅈ\n- ㅂㅇㅂ', answer: '그 남자 그 여자\n- 바이브', index: '81'),
  GameContents(name: 'ㅇㄱㄱ - ㅇㅎㄹ', answer: '유고걸 - 이효리', index: '82'),
  GameContents(name: 'ㅎㄷㄹ ㅇㅈ - ㅎㄱㅁ', answer: '흔들린 우정 - 홍경민', index: '83'),
  GameContents(name: 'ㄱ - ㅈㅇㄷ', answer: '길 - 지오디', index: '84'),
  GameContents(name: 'ㅇㅉㄷ - ㅇㄱ', answer: '어쩌다 - 윤건', index: '85'),
  GameContents(name: 'ㅁㅇ ㄴㅇ - ㅂㅇ', answer: '마이 네임 - 보아', index: '86'),
  GameContents(name: 'ㄱㄴㄱ ㅇㅈㅇ - ㄱㅎㅈ', answer: '그녀가 웃잖아 - 김형중', index: '87'),
  GameContents(
      name: 'ㅈㅅㅅㄷ ㄴㄱㄱㅊㄹ - ㅅㅅㅎ', answer: '전설속의 누군가처럼 - 신승훈', index: '88'),
  GameContents(name: 'ㅁㅇㅎㅇ - ㄱㅁ', answer: '미안해요 - 거미', index: '89'),
  GameContents(name: 'ㅂㄱ ㅅㄷ - ㄱㅂㅅ', answer: '보고 싶다 - 김범수', index: '90'),
  GameContents(name: 'ㅂㅌㄴ - ㅈㅇㄷ', answer: '보통날 - 지오디', index: '91'),
  GameContents(name: 'ㅈㅅ - ㅋ', answer: '진실 - 쿨', index: '92'),
  GameContents(name: 'ㅇㅎㅇ ㅅㄴㅌ\n- ㅇㅇㅂ', answer: '유혹의 소나타\n- 아이비', index: '93'),
  GameContents(name: 'ㅇㅅㄱ - ㄱㅇㅇ', answer: '야상곡 - 김윤아', index: '94'),
  GameContents(name: 'ㅇㅇㄲ\n- ㅇㄷㅎㅂㄷ', answer: '잊을께\n- 윤도현밴드', index: '95'),
  GameContents(name: 'ㅇㅇ - ㅅㅋㅇ', answer: '영원 - 스카이', index: '96'),
  GameContents(
      name: 'ㅂㄹㅁㅂㄹㅁ\n- ㄱㅈㄱ, ㅇㅅㅈㅇㄴㅂ',
      answer: '바람만바람만\n- 김종국, 에스지워너비',
      index: '97'),
  GameContents(name: 'ㄲㅇㅇㄱ - ㅇㄹ', answer: '까만안경 - 이루', index: '98'),
  GameContents(
      name: 'ㄷㅅ ㅁㄴ ㅅㄱ\n- ㅅㄴㅅㄷ', answer: '다시 만난 세계\n- 소녀시대', index: '99'),
  GameContents(name: 'ㅁㅅㅌ - ㅋㄹ', answer: '미스터 - 카라', index: '100')
];
final List<GameContents> music2010 = [
  GameContents(name: 'ㅈㅅㄹ - ㅇㅇㅇ', answer: '잔소리 - 아이유', index: '1'),
  GameContents(name: 'ㅈㅇㄷ ㅁ ㅂㄴ\n- ㅌㅍㅇ', answer: '죽어도 못 보내\n- 투피엠', index: '2'),
  GameContents(name: 'ㄴ ㄸㅁㅇ ㅁㅊ\n- ㅌㅇㄹ', answer: '너 때문에 미쳐\n- 티아라', index: '3'),
  GameContents(name: 'ㅂㅁ ㅈ ㅁㄷㄹ\n- ㅇㅁ', answer: '밥만 잘 먹더라\n- 옴므', index: '4'),
  GameContents(name: 'ㄹㅍ - ㅋㄹ', answer: '루팡 - 카라', index: '5'),
  GameContents(name: 'ㅇㅌㅇㅇ\n-ㅆㅇㅂㄹ', answer: '외톨이야\n- 씨엔블루', index: '6'),
  GameContents(name: 'ㄱㅂ\n- ㄸㄱㅇ ㄱㅈ', answer: '고백\n- 뜨거운 감자', index: '7'),
  GameContents(name: 'ㄴ ㅂㅈㅇ ㄴㄹ\n- ㅂ', answer: '널 붙잡을 노래\n- 비', index: '8'),
  GameContents(name: 'ㄹㄹㅍㄹ\n- ㅌㅇㄹ', answer: '롤리폴리\n- 티아라', index: '9'),
  GameContents(
      name: 'ㄴㄱ ㅈㅇ ㅈ\nㄴㄱ - ㅌㅇㄴㅇ', answer: '내가 제일 잘\n나가 - 투애니원', index: '10'),
  GameContents(name: 'ㅂㄱ ㅇㄴ ㄴㅇ\n- ㅂㅅㅌ', answer: '비가 오는 날엔\n- 비스트', index: '11'),
  GameContents(name: 'ㅈㅇ ㄴ - ㅇㅇㅇ', answer: '좋은 날 - 아이유', index: '12'),
  GameContents(
      name: 'ㅇㄴㅇㄹㄱ\nㅁㅎㅈㅁ - ㄷㅂㅊ', answer: '안녕이라고\n말하지마 - 다비치', index: '13'),
  GameContents(name: 'ㅂㅂㄷㅊ - ㅅㅋㄹ', answer: '별빛달빛 - 시크릿', index: '14'),
  GameContents(name: 'ㅅㅇㅂㅇ - ㅅㅋㄹ', answer: '샤이보이 - 시크릿', index: '15'),
  GameContents(name: 'ㄱㄴㅅㅌㅇ - ㅆㅇ', answer: '강남스타일 - 싸이', index: '16'),
  GameContents(name: 'ㄴㅎㅈ - ㅆㅅㅌ', answer: '나혼자 - 씨스타', index: '17'),
  GameContents(name: 'ㅎㄹ ㄲ - ㅇㅇㅇ', answer: '하루 끝 - 아이유', index: '18'),
  GameContents(name: 'ㅊㅅㄹ\n- ㅂㅅㅋㅂㅅㅋ', answer: '첫사랑\n- 버스커버스커', index: '19'),
  GameContents(
      name: 'ㄴㄹ ㅅㄹㅎㄷ\nㅅㄹㅇ - ㅎㄱ', answer: '나를 사랑했던\n사람아 - ㅎㄱ', index: '20'),
  GameContents(name: 'ㅇㅈㅈㅁ ㅈㅂ\n- ㅋㅇㅇ', answer: '이러지마 제발\n- 케이윌', index: '21'),
  GameContents(name: 'ㄴㄹ ㄴ - ㅇㅇㅇ', answer: '너랑 나 - 아이유', index: '22'),
  GameContents(name: 'ㅂㅇㅈㄱ - ㅇㅇㄹ', answer: '보여줄게 - 에일리', index: '23'),
  GameContents(name: 'ㅇㄹㅇ ㅁㅇㅇ\n- ㅍㅁㄴ', answer: '이름이 뭐예요\n- 포미닛', index: '24'),
  GameContents(name: 'ㅂㄲ ㅇㄷ\n- ㅂㅅㅋㅂㅅㅋ', answer: '벚꽃 엔딩\n- 버스커버스커', index: '25'),
  GameContents(name: 'ㅊ ㅅㄹㄴ\n- ㅇㅍㅇㅅ', answer: '첫 사랑니\n- 에프엑스', index: '26'),
  GameContents(name: 'ㅇㅅㅎ - ㅂㅎㅅ', answer: '야생화 - 박효신', index: '27'),
  GameContents(name: 'ㄱㅇㅇㅇ ㅁㄴㅇ\n- ㅇㅇㅇ', answer: '금요일에 만나요\n- 아이유', index: '28'),
  GameContents(
      name: 'ㄱ ㅈㅇ ㄱㄷㄹ\nㅁㄴ - ㅇㅅㅎ', answer: '그 중에 그대를\n만나 - 이선희', index: '29'),
  GameContents(
      name: 'ㅎㅇㄹㅂㅇ ㄲ\n- ㅅㅇ, ㄹㅇㄴ', answer: '한여름밤의 꿀\n- 산이, 레이나', index: '30'),
  GameContents(name: 'ㄴㄹㄱ ㄴㅇㅇ\n- ㅇㅇㄹ', answer: '노래가 늘었어\n- 에일리', index: '31'),
  GameContents(name: 'ㄲㅌㄹㄴ\n- ㅇㄹㅈㅋㄹㅁ', answer: '까탈레나\n- 오렌지카라멜', index: '32'),
  GameContents(
      name: 'ㅇㄹㄱㅁ\nㄱㄹㅈㅁㅈ\n-ㅂㅇㅇ', answer: '이럴거면\n그러지말지\n- 백아연', index: '33'),
  GameContents(name: 'ㄲㄴ ㅁㅇㅇ\n- ㅈㅇㅇㅌ', answer: '꺼내 먹어요\n- 자이언티', index: '34'),
  GameContents(name: 'ㅇㅇㅎ ㅂ\n- ㄹㄲ, ㅇㅈ', answer: '우연히 봄\n- 로꼬, 유주', index: '35'),
  GameContents(
      name: 'ㄷㄹ ㄴㅈ ㅁㄱ ㄴ\n- ㅁㅆㅇㅇ', answer: '다른 남자 말고 너\n- 미쓰에이', index: '36'),
  GameContents(name: 'ㄷㅅㄹ\n- ㄷㅂㅊ', answer: '두사랑\n- 다비치', index: '37'),
  GameContents(name: 'ㅇㅇㅇㅇ\n- ㅁㅁㅁ', answer: '음오아예\n- 마마무', index: '38'),
  GameContents(
      name: 'ㅇㄴㅂㅌ ㅇㄹㄴ\n- ㅇㅈㅊㄱ', answer: '오늘부터 우리는\n- 여자친구', index: '39'),
  GameContents(name: 'ㄱㅎㅁㅇㅅ\n- ㄱㅎ', answer: '광화문에서\n- 규현', index: '40'),
  GameContents(name: 'ㅅㄱㅇ ㄷㄹㅅ\n- ㅇㅈㅍㄱ', answer: '시간을 달려서\n- 여자친구', index: '41'),
  GameContents(
      name: 'ㄴㄱ ㅈㅈㄹ ㅅㄹ\n- ㅇㅊㅈ', answer: '내가 저지른 사랑\n- 임창정', index: '42'),
  GameContents(name: 'ㅂㄴ\n- ㅂㅌㅅㄴㄷ', answer: '봄날\n- 방탄소년단', index: '43'),
  GameContents(name: 'ㄴ ㄴㅁ ㅁㄹㄱ\n- ㅎㅇㅈ', answer: '널 너무 모르고\n- 헤이즈', index: '44'),
  GameContents(name: 'ㄱㄷㄹㄴ ㅅㅊ\n- ㅎㄷㄱ', answer: '그대라는 사치\n- 한동근', index: '45'),
  GameContents(
      name: 'ㅁㄷ ㄴ ㅁㄷ\nㅅㄱ - ㅍㅋ', answer: '모든 날 모든\n순간 - 폴킴', index: '46'),
  GameContents(name: 'ㅂㅇ ㅂㄴㄴ ㅂ\n- ㅁㅁㅁ', answer: '별이 빛나는 밤\n- 마마무', index: '47'),
  GameContents(
      name: 'ㅈㅇ ㄱㄷㅇ\nㅇㅎ ㅅ\n- ㅂㅌㅅㄴㄷ',
      answer: '작은 것들을\n위한 시\n- 방탄소년단',
      index: '48'),
  GameContents(name: 'ㄴㄹ ㅁㄴ - ㅍㅋ', answer: '너를 만나 - 폴킴', index: '49'),
  GameContents(
      name: 'ㅈㅈㅎㄴ\nㅇㅇㄷㅇ ㅇㅎ\n- ㅈㄴㅂ',
      answer: '주저하는\n연인들을 위해\n- 잔나비',
      index: '50'),
  GameContents(name: 'ㅂㅍㅈ - ㅇㅇㅇ', answer: '밤편지 - 아이유', index: '51'),
  GameContents(
      name: 'ㅊㄴㅊㄹ ㄴㅇㄱ\nㄱㅇㄷ - ㅇㅇㄹ', answer: '첫눈처럼 너에게\n가겠다 - 에일리', index: '52'),
  GameContents(
      name: 'ㅂ ㅅㄹ ㅂㄲ ㅁㄱ\n- ㅎㅇㅍ, ㅇㅇㅇ',
      answer: '봄 사랑 벚꽃 말고\n- 하이포, 아이유',
      index: '53'),
  GameContents(name: 'ㅇㄷㅇㄷ\n- ㅇㅆㄷㅁㅅ', answer: '어디에도\n- 엠씨더맥스', index: '54'),
  GameContents(name: 'ㅂㄹㄱㅇ\n- ㄴㅇ', answer: '바람기억\n- 나얼', index: '55'),
  GameContents(name: 'ㅅㅁ - ㅁㄹㅁㅅ', answer: '선물 - 멜로망스', index: '56'),
  GameContents(name: 'ㄴㅇ ㅇㅁ - ㅇㅇㅇ', answer: '너의 의미 - 아이유', index: '57'),
  GameContents(name: 'ㅈㄴ - ㅇㅈㅅ', answer: '좋니 - 윤종신', index: '58'),
  GameContents(
      name: 'ㅂㄷ ㅇㄱ ㄱㄹㅅ\n- ㅎㅇㅈ', answer: '비도 오고 그래서\n- 헤이즈', index: '59'),
  GameContents(
      name: 'ㅇㅈㄹ ㅈㄹ\n- ㅂㅃㄱㅅㅊㄱ', answer: '우주를 줄게\n- 볼빨간사춘기', index: '60'),
  GameContents(
      name: 'ㅁㄹ ㅁㄹ\nㅋㄹㅅㅁㅅ\n- ㅇㅇㅇ', answer: '미리 메리\n크리스마스\n- 아이유', index: '61'),
  GameContents(name: 'ㄸ ㄷㅅ ㅅㄹ\n- ㅇㅊㅈ', answer: '또 다시 사랑\n- 임창정', index: '62'),
  GameContents(
      name: 'ㄴ ㅅㄹㅎㅈ ㅇㅇ\n- ㅇㅂㅈㅋㅍ', answer: '널 사랑하지 않아\n- 어반자카파', index: '63'),
  GameContents(name: 'ㅆ\n- ㅅㅇ, ㅈㄱㄱ', answer: '썸\n- 소유, 정기고', index: '64'),
  GameContents(name: 'ㅅㄹㅇ ㅎㄷ\n- ㅇㅇㅋ', answer: '사랑을 했다\n- 아이콘', index: '65'),
  GameContents(name: 'ㄲㅅㄹ - ㄱㅂㅅ', answer: '끝사랑 - 김범수', index: '66'),
  GameContents(name: 'ㅃㄱ ㅁ\n- ㄹㄷㅂㅂ', answer: '빨간 맛\n- 레드벨벳', index: '67'),
  GameContents(name: 'ㅍㄹㅌ - ㅇㅇㅇ', answer: '팔레트 - 아이유', index: '68'),
  GameContents(
      name: 'ㅈㄷㄱ ㅁㅎ\n- ㅂㅃㄱㅅㅊㄱ', answer: '좋다고 말해\n- 볼빨간사춘기', index: '69'),
  GameContents(name: 'ㄱㅈㅁㅇㅇ ㄱㄷ\n- ㅇㅈ', answer: '걱정말아요 그대\n- 이적', index: '70'),
  GameContents(
      name: 'ㅇㅅ ㅂㅂㄷ\n- ㅂㅅㅋ ㅂㅅㅋ', answer: '여수 밤바다\n- 버스커 버스커', index: '71'),
  GameContents(name: 'ㄸㄷㄸㄷ\n- ㅂㄹㅍㅋ', answer: '뚜두뚜두\n- 블랙핑크', index: '72'),
  GameContents(name: 'ㅈㄴㅇㄷ\n- ㄴㄹ', answer: '지나오다\n- 닐로', index: '73'),
  GameContents(name: 'ㄱㄴㅊㄹ\n- ㅈㄷㅊ', answer: '그날처럼\n- 장덕철', index: '74'),
  GameContents(
      name: 'ㄴㅁ ㅇㄷㄴ ㅇㅇ\n- ㅂㅃㄱㅅㅊㄱ', answer: '나만 안되는 연애\n- 볼빨간사춘기', index: '75'),
  GameContents(name: 'ㅎㅅ - ㅇㅎㅇ', answer: '한숨 - 이하이', index: '76'),
  GameContents(name: 'ㄴㅇㄷㅁ\n- ㅈㅅㅎ', answer: '너였다면 - 정승환', index: '77'),
  GameContents(name: 'ㅇㅎ\n- ㅂㅃㄱㅅㅊㄱ', answer: '여행 - 볼빨간사춘기', index: '78'),
  GameContents(name: 'ㄱㄹㅇㅎㄷ\n- ㅂㅌㅂ', answer: '그리워하다\n- 비투비', index: '79'),
  GameContents(name: 'ㅁㅈㅁㅊㄹ\n- ㅂㄹㅍㅋ', answer: '마지막처럼 - 블랙핑크', index: '80'),
  GameContents(name: 'ㅂㅂㅂ - ㅂㅂ', answer: '뱅뱅뱅 - 빅뱅', index: '81'),
  GameContents(name: 'ㅇㄴㅈㅌ - ㅇㄴㅇ', answer: '에너제틱 - 워너원', index: '82'),
  GameContents(name: 'ㅂㅈㄴ - ㅂㄹㅍㅋ', answer: '불장난 - 블랙핑크', index: '83'),
  GameContents(name: 'ㅇㅎㄷㄱ- ㅈㅇㅇㅌ', answer: '양화대교 - 자이언티', index: '84'),
  GameContents(name: 'ㅇㅇㅈ- ㅈㅈㅇ', answer: '안아줘 - 정준일', index: '85'),
  GameContents(name: 'ㅅㄴ - ㅇㅎ', answer: '소녀 - 오혁', index: '86'),
  GameContents(name: 'ㄱㄹㅅㄷ - ㅂㅇㅇ', answer: '가라사대 - 비와이', index: '87'),
  GameContents(name: 'ㅆ ㅌㄱㅇ\n- ㅂㅃㄱㅅㅊㄱ', answer: '썸 탈꺼야\n- 볼빨간사춘기', index: '88'),
  GameContents(name: 'ㅂ - ㅍㅋ', answer: '비 - 폴킴', index: '89'),
  GameContents(name: 'ㅇㄸㅇㄲ - ㅆㅇ', answer: '어땠을까 - 싸이', index: '90'),
  GameContents(name: 'ㄷㅇㅇㅈㅁ - ㅎㅇㅈ', answer: '돌아오지마 - 헤이즈', index: '91'),
  GameContents(name: 'ㅃㅃ - ㅇㅇㅇ', answer: '삐삐 - 아이유', index: '92'),
  GameContents(name: 'ㅅ - ㅂㅎㅅ', answer: '숨 - 박효신', index: '93'),
  GameContents(name: 'ㅇㅇㅇㅇ - ㅎㅇ', answer: '위잉위잉 - 혁오', index: '94'),
  GameContents(name: 'ㅇ ㅅㄹ - ㄷㅂㅊ', answer: '이 사랑 - 다비치', index: '95'),
  GameContents(name: 'ㅅㅁㅅ - ㅇㅇㅇ', answer: '스물셋 - 아이유', index: '96'),
  GameContents(
      name: 'ㅊㅇㄴ ㅅㄹㅇㄹㄱ\n- ㅂㅅㅋ ㅂㅅㅋ',
      answer: '처음엔 사랑이란게\n- 버스커 버스커',
      index: '97'),
  GameContents(
      name: 'ㄱㄸ ㅎㅇㅈㅁ ㄷ\n- ㄹㅇㅋ', answer: '그때 헤어지면 돼\n- 로이킴', index: '98'),
  GameContents(name: 'ㅍ ㄸ ㄴㅁ\n- ㅂㅌㅅㄴㄷ', answer: '피 땀 눈물\n- 방탄소년단', index: '99'),
  GameContents(
      name: 'ㅇㄹ ㄴ ㅇㄹ ㅂ\n- ㅇㅁ', answer: '오랜 날 오랜 밤\n- 악뮤', index: '100'),
];
final List<GameContents> music2020 = [
  GameContents(name: 'ㅇㅁㄴㄹ - ㅈㅋ', answer: '아무노래 - 지코', index: '1'),
  GameContents(name: 'ㅇㄹㅎ - ㅈㅈㅅ', answer: '아로하 - 조정석', index: '2'),
  GameContents(name: 'ㅇㅇ - ㅇㅇㅇ', answer: '에잇 - 아이유', index: '3'),
  GameContents(name: 'ㅅㅈ - ㄱㅎ', answer: '시작 - 가호', index: '4'),
  GameContents(name: 'ㅁㅇㅇ ㄷㄹㅇ\n- ㅇㅇㅇ', answer: '마음을 드려요\n- 아이유', index: '5'),
  GameContents(name: 'ㅊㅇㅊㄹ\n- ㅇㅆㄷㅁㅅ', answer: '처음처럼\n- 엠씨더맥스', index: '6'),
  GameContents(name: 'ㅅㅉ ㅅㄹㅇ\n- ㅇㅁㅇㄱ', answer: '살짝 설렜어\n- 오마이걸', index: '7'),
  GameContents(
      name: 'ㄷㅅ ㅇㄱ\nㅂㄷㄱ - ㅆㅆㄹ', answer: '다시 여기\n바닷가\n- ㅆㅆㄹ', index: '8'),
  GameContents(
      name: 'ㅅㄹㅎㄱ\nㄷ ㅈ ㅇㅇㅇ\n- ㅈㅁㄷ', answer: '사랑하게\n될 줄 알았어\n- ㅈㅁㄷ', index: '9'),
  GameContents(
      name: 'ㄴㄹ ㅅㄹㅎㄱ\nㅇㅇ - ㅂㅎ', answer: '너를 사랑하고\n있어 - 백현', index: '10'),
  GameContents(name: 'ㄴㄴㄴㄴ - ㅈㅅ', answer: '눈누난나 - 제시', index: '11'),
  GameContents(
      name: 'ㅅㄷ ㄲㅇ\nㅁㅇ ㅈㄷ\n- ㅂㅎㅇ', answer: '시든 꽃에\n물을 주듯\n- 박혜원', index: '12'),
  GameContents(
      name: 'ㅎㄹㅎㅈ ㅇㅇ\nㄱㅂ - ㄱㅎ', answer: '화려하지 않은\n고백 - 규현', index: '13'),
  GameContents(name: 'ㅍㅈㅁㅊ\n- ㅎㅇㅇ', answer: '포장마차\n- 황인욱', index: '14'),
  GameContents(
      name: 'ㅅㄹㅇ ㅇㅅㅇ\nㅇㅇㄷㅁ\n- ㅇㅈㅎ',
      answer: '사랑에 연습이\n있었다면\n- 임재현',
      index: '15'),
  GameContents(
      name: 'ㄱㄷ ㄱㅇ\nㄴㅅㄹ\n- ㅇㅂㅈㅋㅍ', answer: '그대 고운\n내사랑\n- 어반자카파', index: '16'),
  GameContents(name: 'ㅅㅊ - ㅇㅇㅈ', answer: '시차 - 우원재', index: '17'),
  GameContents(name: 'ㄷㄷㄷㄷ\n- ㅇㅈㅇㅇㄷ', answer: '덤디덤디\n- 여자아이들', index: '18'),
  GameContents(name: 'ㄱㄷㄹㄴ ㅅ\n- ㅌㅇ', answer: '그대라는 시\n- 태연', index: '19'),
  GameContents(name: 'ㄹㄹ\n- ㅂㄹㅇㅂㄱㅅ', answer: '롤린\n- 브레이브걸스', index: '20'),
  GameContents(name: 'ㄹㅇㄹ - ㅇㅇㅇ', answer: '라일락 - 아이유', index: '21'),
  GameContents(name: 'ㅅㅎㄷ - ㅇㅁㅈ', answer: '신호등 - 이무진', index: '22'),
  GameContents(name: 'ㅂㅎㄴㅇ ㅂㅇ\n- ㄱㅅ', answer: '밤하늘의 별을\n- 경서', index: '23'),
  GameContents(
      name: 'ㅇㄹㄷ ㄴㄹ\n- ㅅㅌㄷ ㅇㄱ', answer: '오래된 노래\n- 스탠딩 에그', index: '24'),
  GameContents(name: 'ㅊㅁㅂㄹ\n- ㅂㄹㅇㅂㄱㅅ', answer: '치맛바람\n- 브레이브걸스', index: '25'),
  GameContents(
      name: 'ㅇㅇㅇ ㄴㅇ ㅂㄷ\n- ㅇㅇㅇ', answer: '아이와 나의 바다\n- 아이유', index: '26'),
  GameContents(name: 'ㅁㄹㅇ - ㅎㅅ', answer: '마리아 - 화사', index: '27'),
  GameContents(name: 'ㅈㅈㅁ\n- ㅎㅅ ㄹㄲ', answer: '주지마\n- 화사, 로꼬', index: '28'),
  GameContents(
      name: 'ㅈㅇ ㅇㅈ\nㅇㄴㅇ - ㅈㅂㅈ', answer: '잠이 오질\n않네요 - 장범준', index: '29'),
  GameContents(name: 'ㅅㄹㅇㄱ ㅂ\n- ㅁㄹㅁㅅ', answer: '사랑인가 봐\n- 멜로망스', index: '30'),
  GameContents(
      name: 'ㅅㄹㅇ ㄴ\nㄷㅁㄱ - ㅇㅇㅇ', answer: '사랑은 늘\n도망가 - 임영웅', index: '31'),
  GameContents(name: 'ㅊㅈㄱㅂ - ㄱㅁㅅ', answer: '취중고백 - 김민석', index: '32'),
  GameContents(name: 'ㅂㅇㄹㄱㅇㄱㅇ\n- ㅂㅂ', answer: '봄여름가을겨울\n- 빅뱅', index: '33'),
  GameContents(name: 'ㅈㅇㄹㄱ ㅎㅈ\n- ㅂㄴㅌ', answer: '정이라고 하자\n- 빅나티', index: '34'),
  GameContents(name: 'ㅎㅈㅁㅁ\n- ㅅㅋㄷㅁ', answer: '회전목마\n- 소코도모', index: '35'),
  GameContents(name: 'ㄷㄹㅁ - ㅇㅇㅇ', answer: '드라마 - 아이유', index: '36'),
  GameContents(name: 'ㄴㅇ ㅁㄷ ㅅㄱ\n- ㅅㅅㄱ', answer: '너의 모든 순간\n- 성시경', index: '37'),
  GameContents(name: 'ㅅㅃ - ㅈㅋ', answer: '새삥 - 지코', index: '38'),
  GameContents(name: 'ㄴㅇ ㅇㅈㅇ\n- ㅇㅁㅈ', answer: '눈이 오잖아\n- 이무진', index: '39'),
  GameContents(name: 'ㅅㄱㅇ ㅈㅍㅅ\n- ㅇㅎ', answer: '사건의 지평선\n- 윤하', index: '40'),
  GameContents(name: 'ㄱㅂ - ㅅㅅㅊ', answer: '고백\n- 십센치', index: '41'),
  GameContents(name: 'ㄴㅎ - ㅇㅁ', answer: '낙하 - 악뮤', index: '42'),
  GameContents(
      name: 'ㅇㄴㄷ ㅂㄴㄴ\nㄴㅇㄱ -ㅁㅋㅌ', answer: '오늘도 빛나는\n너에게 -마크툽', index: '43'),
  GameContents(name: 'ㅊㄱㄹ ㅂㄹ\n- ㅅㄷ', answer: '취기를 빌려\n- 산들', index: '44'),
  GameContents(name: 'ㅎㄹㅇㅇ ㄲ\n- ㅇㅁ', answer: '후라이의 꿈\n- 악뮤', index: '45'),
  GameContents(name: 'ㅎㅇㅈㅈ ㅁㅎㅇ\n- ㅂㅈㅈ', answer: '헤어지자 말해요\n- 박재정', index: '46'),
  GameContents(
      name: 'ㅅㅁㅇㅅ ㄲㅇ\nㅍㅇㄷ - ㅇㄷ', answer: '사막에서 꽃을\n피우듯 - 우디', index: '47'),
  GameContents(name: 'ㅋㅋ\n- ㅇㅈㅇㅇㄷ', answer: '퀸카\n- 여자아이들', index: '48'),
  GameContents(name: 'ㅈ ㅈㄴㅈ ㅇㄹ\n- ㅊㅇㄹ', answer: '잘 지내자 우리\n- 최유리', index: '49'),
  GameContents(name: 'ㅍㅇㅌ ㅎㅇㅈ\n- ㅂㅅㅅ', answer: '파이팅 해야지\n- 부석순', index: '50'),
  GameContents(name: 'ㅂㅇㄱ - ㅂㅂ', answer: '밤양갱 - 비비', index: '51'),
  GameContents(name: 'ㅂㅇ ㄹㅅㄷ\n- ㅇㅈㅎ', answer: '비의 랩소디\n- 임재현', index: '52'),
  GameContents(name: 'ㅇㅍㅅㄷ - ㅇㅁㅈ', answer: '에피소드 - 이무진', index: '53'),
  GameContents(
      name: 'ㄱㄷㅁ ㅇㅆㄷ\n- ㄴㄷㅋㄴㅅ', answer: '그대만 있다면\n- 너드커넥션', index: '54'),
  GameContents(name: 'ㅇㅅ - ㅂㅈ', answer: '인사 - 범진', index: '55'),
  GameContents(name: 'ㄱ ㅇ ㄱㅌ - ㄹㅇㅈ', answer: '겟 어 기타 - 라이즈', index: '56'),
  GameContents(
      name: 'ㅎ ㅍㅇㅈㄱ\nㄷㅅ ㅇㄱ\n- ㄷㅇㅅㅅ',
      answer: '한 페이지가\n될 수 있게\n- 데이식스',
      index: '57'),
  GameContents(name: 'ㅎㅂ ㅂㅇ\n- ㄴㅈㅅ', answer: '하입 보이\n- 뉴진스', index: '58'),
  GameContents(name: 'ㅅㅍ ㅅㅇ\n- ㄴㅈㅅ', answer: '슈퍼 샤이\n- 뉴진스', index: '59'),
  GameContents(name: 'ㄷㅌ - ㄴㅈㅅ', answer: '디토 - 뉴진스', index: '60'),
  GameContents(
      name: 'ㅅㄹㅎ ㅅㅂㅇ\n- ㅂㅃㄱㅅㅊㄱ', answer: '사랑할 수밖에\n- 볼빨간사춘기', index: '61'),
  GameContents(
      name: 'ㄱㅁ ㅅㅇㅇ\nㅍㅇㄴ ㅈㅁ\n- ㅎㅇㅋ',
      answer: '건물 사이에\n피어난 장미\n- 하이키',
      index: '62'),
  GameContents(name: 'ㄷㄹㅁ - ㅇㅅㅍ', answer: '드라마 - 에스파', index: '63'),
  GameContents(name: 'ㅌㄷ ㅂㅇ\n- ㅅㅌㅇㅆ', answer: '테디 베어\n- 스테이씨', index: '64'),
  GameContents(name: 'ㅅㅇㄱ - ㅅㅂㅌ', answer: '손오공 - 세븐틴', index: '65'),
  GameContents(name: 'ㄲ - ㅈㅅ', answer: '꽃 - 지수', index: '66'),
  GameContents(name: 'ㄱㄹㄷㅇㅅ\n- ㅅㅅㅊ', answer: '그라데이션 - ㅅㅅㅊ', index: '67'),
  GameContents(name: 'ㅁㄹ - ㅎㄱ', answer: '물론 - 허각', index: '68'),
  GameContents(name: 'ㅇㄹㅂ - ㅇㅇㅂ', answer: '일레븐 - 아이브', index: '69'),
  GameContents(name: 'ㅍㅇㄹㅅ\n-  ㄹㅅㄹㅍ', answer: '피어리스\n- 르세라핌', index: '70'),
  GameContents(name: 'ㅇㄹㅌㄱㄹ\n- ㅇㅎ', answer: '오르트구름\n- 윤하', index: '71'),
  GameContents(name: 'ㅂㅇ ㄴㄴ\nㄴㅇㄱ - ㄷ', answer: '빛이 나는\n너에게 - 던', index: '72'),
  GameContents(name: 'ㄴㅅㅅ - ㅅㅎㅇ', answer: '니소식 - 송하예', index: '73'),
  GameContents(name: 'ㅈㄲ ㅅㄱ ㄷㄲ\n- ㅇㅁㅈ', answer: '잠깐 시간 될까\n- 이무진', index: '74'),
  GameContents(name: 'ㅁㅇ ㅂ - ㅇㅇㄷ', answer: '마이 백 - 아이들', index: '75'),
  GameContents(name: 'ㄹㅂ ㄷㅇㅂ - ㅇㅇㅂ', answer: '러브 다이브 - 아이브', index: '76'),
  GameContents(name: 'ㅌㅁㅂ - ㅇㅇㄷ', answer: '톰보이 - 아이들', index: '77'),
  GameContents(name: 'ㅍ ㅁㅇ ㄹㄷ\n- ㄹㄷㅂㅂ', answer: '필 마이 리듬\n- 레드벨벳', index: '78'),
  GameContents(name: 'ㅇㅌㅅ - ㄴㅈㅅ', answer: '어텐션 - 뉴진스', index: '79'),
  GameContents(name: 'ㅇㅍㅌ ㄹㅇㅋ\n- ㅇㅇㅂ', answer: '애프터 라이크\n- 아이브', index: '80'),
  GameContents(name: 'ㄴㅅㅌ ㄹㅂ\n- ㅇㅅㅍ', answer: '넥스트 레벨\n- 에스파', index: '81'),
  GameContents(name: 'ㄱㄴㄷㄹ - ㅂㅈㅂ', answer: '가나다라 - 박재범', index: '82'),
  GameContents(name: 'ㅅㅌㅂㄹ ㅁ\n- ㅇㅇㅇ', answer: '스트로베리 문\n- 아이유', index: '83'),
  GameContents(name: 'ㄴㄹ ㅅㄱㅎ\n- ㅈㅅㅋ', answer: '너를 생각해\n- 주시크', index: '84'),
  GameContents(name: 'ㅇㅈㄴ ㅅㄹㅎ\n- ㅋㅇㅅ', answer: '언제나 사랑해\n- 케이시', index: '85'),
  GameContents(
      name: 'ㅇㄹㄱ ㅎㅇㅈㅇ\nㅎㄷ ㅇㅇ - ㅂㅂ',
      answer: '우리가 헤어져야\n했던 이유 - 비비',
      index: '86'),
  GameContents(name: 'ㄷㄱㅂㅂ - ㅇㅅㅍ', answer: '도깨비불 - 에스파', index: '87'),
  GameContents(name: 'ㅅㄹ - ㅅㅅㅊ', answer: '서랍 - ㅅㅅㅊ', index: '88'),
  GameContents(name: 'ㄴㄷ - ㅇㅇㄷ', answer: '누드 - 아이들', index: '89'),
  GameContents(name: 'ㄱㅇㅈ - ㅇㅇㅇ', answer: '겨울잠 - 아이유', index: '90'),
  GameContents(name: 'ㅂㅇ ㄷㅅ - ㅇㅁㅈ', answer: '비와 당신 - 이무진', index: '100')
];

final List<GameContents> movie = [
  GameContents(name: 'assets/movie/오징어게임.png', answer: '우린 깐부잖아', index: '1'),
  GameContents(
      name: 'assets/movie/해바라기.png',
      answer: '꼭 그렇게..\n다 가져가야만..\n속이 후련했냐!',
      index: '2'),
  GameContents(name: 'assets/movie/곡성.png', answer: '뭣이 중헌디!', index: '3'),
  GameContents(
      name: 'assets/movie/박하사탕.png', answer: '나 다시 돌아갈래 ~', index: '4'),
  GameContents(
      name: 'assets/movie/극한직업.png',
      answer: '지금까지\n이런 맛은 없었다.\n이것은 갈비인가 통닭인가',
      index: '5'),
  GameContents(name: 'assets/movie/타짜.png', answer: '묻고 더블로 가!', index: '6'),
  GameContents(
      name: 'assets/movie/지붕뚫고 하이킥.png', answer: '이 빵꾸똥꾸야!', index: '7'),
  GameContents(
      name: 'assets/movie/아저씨.png', answer: '이거 방탄유리야\n이 개**야!', index: '8'),
  GameContents(
      name: 'assets/movie/내부자들.png',
      answer: '모히또 가가지고\n몰디브나 한 잔 할라니까',
      index: '9'),
  GameContents(
      name: 'assets/movie/도깨비.png',
      answer: '날이 좋아서,\n날이 좋지 않아서,\n날이 적당해서\n모든 날이 좋았다',
      index: '10'),
  GameContents(name: 'assets/movie/타짜2.png', answer: '쏠 수 있어!', index: '11'),
  GameContents(name: 'assets/movie/최고의 사랑.png', answer: '극 뽁 ~', index: '12'),
  GameContents(
      name: 'assets/movie/어게인 마이 라이프.png', answer: '진행시켜.', index: '13'),
  GameContents(name: 'assets/movie/야인시대.png', answer: '4딸라', index: '14'),
  GameContents(
      name: 'assets/movie/기생충.png', answer: '너는 다 계획이 있구나', index: '15'),
  GameContents(
      name: 'assets/movie/친구.png', answer: '느그 아부지 머하시노.', index: '16'),
  GameContents(
      name: 'assets/movie/사랑했나봐.png', answer: '예나..선정이 딸이에요', index: '17'),
  GameContents(
      name: 'assets/movie/타짜3.png',
      answer: '예림이! 그 패 봐봐,\n혹시 장이야?',
      index: '18'),
  GameContents(
      name: 'assets/movie/상속자들.png', answer: '나, 너 좋아하냐?', index: '19'),
  GameContents(
      name: 'assets/movie/부당거래.png',
      answer: '호의가 계속되면,\n그게 권리인 줄 알아요',
      index: '20'),
  GameContents(name: 'assets/movie/아이리스.png', answer: '아악 안돼', index: '21'),
  GameContents(
      name: 'assets/movie/천국의 계단.png', answer: '사랑은, 돌아오는 거야 ~', index: '22'),
  GameContents(
      name: 'assets/movie/파리의 연인.png', answer: '이 안에 너 있다', index: '23'),
  GameContents(
      name: 'assets/movie/내 머리속의 지우개.png',
      answer: '이거 마시면\n나랑 사귀는 거다',
      index: '24'),
  GameContents(name: 'assets/movie/올드보이.png', answer: '누구냐, 넌', index: '25'),
  GameContents(
      name: 'assets/movie/친절한 금자씨.png', answer: '너나 잘하세요', index: '26'),
  GameContents(
      name: 'assets/movie/스카이캐슬.png', answer: '전적으로 저를\n믿으셔야 합니다', index: '27'),
  GameContents(name: 'assets/movie/더글로리.png', answer: '멋지다 연진아 ~', index: '28'),
  GameContents(
      name: 'assets/movie/살인의추억.png', answer: '밥은 먹고 다니냐?', index: '29'),
  GameContents(
      name: 'assets/movie/범죄도시.png', answer: '어, 아직 싱글이야', index: '30'),
  GameContents(
      name: 'assets/movie/태조 왕건.png',
      answer: '누구인가?\n누가 기침소리를\n내었는가?',
      index: '31'),
  GameContents(
      name: 'assets/movie/어벤져스(인피니티 워).png', answer: '와칸다 포에버', index: '32'),
  GameContents(
      name: 'assets/movie/어벤져스(엔드게임).png',
      answer: 'I am Iron Man',
      index: '33'),
  GameContents(name: 'assets/movie/변호인.png', answer: '국가란 국민입니다!', index: '34'),
  GameContents(
      name: 'assets/movie/겨울왕국1.png',
      answer: 'Do you wanna build a snowman?',
      index: '35'),
  GameContents(
      name: 'assets/movie/킹스맨.png',
      answer: 'Manners, Maketh, Man',
      index: '36'),
  GameContents(
      name: 'assets/movie/무한도전.png', answer: '어데가서 무기받노 ~', index: '37'),
  GameContents(
      name: 'assets/movie/바람.png', answer: '내 나이?\n서른마흔다섯살이다.', index: '38'),
  GameContents(name: 'assets/movie/범죄도시2.png', answer: '너 납치된거야', index: '39'),
  GameContents(
      name: 'assets/movie/재벌집 막내아들.png', answer: '몇개고? 밥알 말이다', index: '40'),
  GameContents(
      name: 'assets/movie/상속자들2.png',
      answer: '사탄들의 학교에\n루시퍼의 등장이라..',
      index: '41'),
  GameContents(
      name: 'assets/movie/미래를 보는 소년.png',
      answer: '이따 5시에 호떡집에서\n불이 날거에요',
      index: '42'),
  GameContents(
      name: 'assets/movie/쌈마이웨이.png',
      answer: '예쁜 척 하는게 아니라\n예쁘게 태어난곤데 ~',
      index: '43'),
  GameContents(name: 'assets/movie/러브레터.png', answer: '오겡끼데스까 ~', index: '44'),
  GameContents(name: 'assets/movie/암살.png', answer: '구멍이 두개지요', index: '45'),
  GameContents(
      name: 'assets/movie/명량.png',
      answer: '신에게는 아직\n12척의 배가 남아있사옵니다',
      index: '46'),
  GameContents(name: 'assets/movie/관상.png', answer: '내가 왕이 될 상인가', index: '47'),
  GameContents(
      name: 'assets/movie/7번방의 선물.png', answer: '예승이 콩먹어 콩 비타민', index: '48'),
  GameContents(
      name: 'assets/movie/가을동화.jpeg',
      answer: '웃기지마\n돈으로 사겠어\n얼마면 돼',
      index: '49'),
  GameContents(name: 'assets/movie/펜트하우스.png', answer: '벌써 떨리는 군', index: '50'),
  GameContents(
      name: 'assets/movie/꽃보다남자.jpeg',
      answer: '시켜줘 그럼\n금잔디 명예소방관',
      index: '51'),
  GameContents(
      name: 'assets/movie/꽃보다남자2.jpeg',
      answer: '하얀 천과\n바람만 있으면\n어 디든 갈 수 있어',
      index: '52'),
  GameContents(
      name: 'assets/movie/다모.jpeg', answer: '아프냐 나도 아프다', index: '53'),
  GameContents(
      name: 'assets/movie/로망스.jpeg',
      answer: '난 선생이고\n넌 학생이야',
      index: '54'),
  GameContents(
      name: 'assets/movie/말아톤.jpeg',
      answer: '초원이 다리는\n백만불짜리 다리',
      index: '55'),
  GameContents(
      name: 'assets/movie/명성황후.jpeg', answer: '내가 조선의 국모다', index: '56'),
  GameContents(
      name: 'assets/movie/미스터션샤인.jpeg', answer: '러브가 무엇이오', index: '57'),
  GameContents(name: 'assets/movie/범죄도시.jpeg', answer: '진실의 방으로', index: '58'),
  GameContents(
      name: 'assets/movie/부부의세계.jpeg', answer: '사랑에 빠진게\n죄는 아니잖아', index: '59'),
  GameContents(
      name: 'assets/movie/사랑과전쟁.jpeg', answer: '괜찮아요?\n많이 놀랐죠?', index: '60'),
  GameContents(
      name: 'assets/movie/서울의봄.jpeg',
      answer: '실패하면 반역\n성공하면 혁명 아닙니까',
      index: '61'),
  GameContents(
      name: 'assets/movie/신데렐라 언니.jpeg',
      answer: '연습은 하니\n죽도록하는거야',
      index: '62'),
  GameContents(
      name: 'assets/movie/응팔.jpeg',
      answer: '아이고 김사장\n이거 정말\n반갑구만 반가워요',
      index: '63'),
  GameContents(
      name: 'assets/movie/이누야샤.jpeg',
      answer: '안녕히계세요 여러분~',
      index: '64'),
  GameContents(
      name: 'assets/movie/재벌집 막내아들.jpeg', answer: '도준이 내 손주다', index: '65'),
  GameContents(
      name: 'assets/movie/지붕뚫고하이킥.jpeg',
      answer: '띠드버거사주세요',
      index: '66'),
  GameContents(
      name: 'assets/movie/지붕뚫고하이킥2.jpeg',
      answer: '세경씨\n그렇게 안 봤는데\n정말 무서운 사람이네',
      index: '67'),
  GameContents(
      name: 'assets/movie/친구.jpeg',
      answer: '고마해라\n마이 무따 아이가',
      index: '68'),
  GameContents(
      name: 'assets/movie/친구2.jpeg', answer: '내가 니 시다바리가', index: '69'),
  GameContents(
      name: 'assets/movie/친구3.jpeg', answer: '니가 가라 하와이', index: '70'),
  GameContents(
      name: 'assets/movie/코난.jpeg', answer: '내 이름은 코난\n탐정이죠', index: '71'),
  GameContents(
      name: 'assets/movie/타짜.jpeg', answer: '나 이대 나온 여자야', index: '72'),
  GameContents(
      name: 'assets/movie/파리의 연인2.png',
      answer:
          '저 사람이 내 사람이다\n저 남자가 내 남자다\n왜 말을 못하냐고',
      index: '73'),
];

final List<GameContents> train = [
  GameContents(
      name: '철수와 영희는 오늘 어푸푸동상 앞에서 만나, 앞구르기를 한 뒤, 애인트에서 녹차라떼 샷추가를 먹었다.',
      index: '1'),
  GameContents(
      name: '외로운 도균이는 오늘 오석에서 긴 생머리에 키 163, 청바지에 바람막이를 입은 어여쁜 여학우를 보고 반하였다.',
      index: '2'),
  GameContents(
      name: '9시 뉴스 속보입니다. 현재 24학번 부르심의 세대 새내기들은 다들 귀엽고 깜찍하고 이쁘고 잘생겨서 논란입니다.',
      index: '3'),
];

final List<UpDownGameContents> updown = [
  UpDownGameContents(name: '업다운', explain1: '#과연 #몇일까 #그 숫자는', index: '1'),
  UpDownGameContents(
      name: '1-100',
      explain1: '#조원들이 함께 손을 들고      #지목하면 #외치기',
      explain2: '',
      index: '2'),
  UpDownGameContents(
      name: '정답: 50',
      explain1: '25            up',
      explain2: '80            down',
      index: '3'),
  UpDownGameContents(name: '업다운', explain1: '#과연 #몇일까 #그 숫자는', index: '4'),
  UpDownGameContents(name: '', explain1: '77', index: '5'),
  UpDownGameContents(name: '업다운', explain1: '#과연 #몇일까 #그 숫자는', index: '6'),
  UpDownGameContents(name: '', explain1: '33', index: '7'),
];

final List<GameContents> petit = [
  GameContents(name: 'ㄹ', index: '1'),
  GameContents(name: 'ㅎ', index: '2'),
  GameContents(name: 'ㅅ', index: '3'),
  GameContents(name: 'ㄷ', index: '4'),
  GameContents(name: 'ㅁ', index: '5'),
];

final List<GameContents> hashtag = [
  GameContents(name: '재수강', index: '1'),
  GameContents(name: '썸', index: '2'),
  GameContents(name: '엄마', index: '3'),
  GameContents(name: '한동대', index: '4'),
];

final List<SizeUpGameContents> sizeup = [
  SizeUpGameContents(
      name: 'assets/images/sizeup_card1.png',
      answer: '9.5cm',
      index: '1',
      explain: '피어나다 카드의 세로 길이는?'),
  SizeUpGameContents(
      name: 'assets/images/sizeup_card2.png',
      answer: '27cm',
      index: '2',
      explain: '초코파이 상자의 가로 길이는?'),
  SizeUpGameContents(
      name: 'assets/images/sizeup_card3.png',
      answer: '사회자가 지정한 사물을 맞춰보세요!',
      index: '3',
      explain: '사회자가 직접 측정합니다!'),
];
